### ISSUE TITLE
Restricting remote endpoints serverside

### ISSUE THREAD

**Issue by Protonull** [jpillora/chisel#102]
Maybe it's just me, but there doesn't seem to be a way to restrict what a client can do post-connection. Though the connection is encrypted and you can add user authentication, what if you want to restrict users to certain remote address and ports? Flip the use case on its head: instead of a restricted set of users allowed to make arbitrary connections, it's arbitrary users allowed to connect to a restricted set of endpoints. How does one do that?

**Comment by aus** [comment]
The server can restrict users to match certain remotes using the [authfile](https://github.com/jpillora/chisel#authentication). See [user.json](https://github.com/jpillora/chisel/blob/master/example/users.json) as an example.

**Comment by Protonull** [comment]
Are users defined in `user.json` limited to one connect? As in would I need to duplicate the restrictions for each unique person using the proxy?
