### ISSUE TITLE
Connection error: websocket: bad handshake

### ISSUE THREAD

**Issue by Jules-Baratoux** [jpillora/chisel#103]
I'm using `jpillora/chisel@sha256:5bbdcdc9716b9a6748ed8b5b3a189f53ba177939ea2b640ba18c3fc24eb2769b` behind `traefik:1.6@sha256:eabb39016917bd43e738fb8bada87be076d4553b5617037922b187c0a656f4a4`.

The client runs on a workstation. The server runs in a remote docker swarm.

```
2019/07/11 22:32:07 client: Connecting to wss://example.com:443
2019/07/11 22:32:07 client: proxy#1:0.0.0.0:1234=>foo:1234: Listening
2019/07/11 22:32:07 client: proxy#2:0.0.0.0:4321=>bar:4321: Listening
2019/07/11 22:32:08 client: Connection error: websocket: bad handshake
```

However the same setup runs fine in a single docker-compose without traefik.

**Comment by jpillora** [comment]
Are all headers proxied by traefik?

**Comment by Jules-Baratoux** [comment]
I'm not sure traefik is messing with any header by default. Is there any way I can test this from within the remote `chisel` container?
