### ISSUE TITLE
auth not working

### ISSUE THREAD

**Issue by vincascm** [jpillora/chisel#104]
server use `--key` and client without `--fingerprint` will Successful connection

**Comment by jpillora** [comment]
```
    --fingerprint, A *strongly recommended* fingerprint string
    to perform host-key validation against the server's public key.
    You may provide just a prefix of the key or the entire string.
    Fingerprint mismatches will close the connection.
```

Leaving out fingerprint will allow any server.

If you want the server to deny clients, you need to use `chisel server --auth "foo:bar"`.
