### ISSUE TITLE
Investigate issues with Minecraft

### ISSUE THREAD

**Issue by Electroid** [jpillora/chisel#108]
Hello, I'm trying to use chisel to transport Minecraft packets (TCP-based game) over HTTP. Here's what I'm currently doing:
```bash
# On the virtual machine running the Minecraft server:
java -jar server.jar nogui &
chisel server -v --port 25566 --proxy tcp://localhost:25565

# On the local machine running the Minecraft client:
chisel client -v http://server-host:25566 25567
```

At first, the client runs out of files:
```
2019/07/23 01:52:07 client: Connecting to ws://localhost:25566
2019/07/23 01:52:07 client: proxy#1:0.0.0.0:25567=>0.0.0.0:25567: Listening
2019/07/23 01:52:07 client: Fingerprint e1:44:44:9d:10:b1:b1:2b:fd:88:f6:9b:13:50:55:d0
2019/07/23 01:52:07 client: Connected (Latency 1.436858ms)
2019/07/23 01:52:43 client: proxy#1:0.0.0.0:25567=>0.0.0.0:25567: Accept error: accept tcp4 0.0.0.0:25567: accept: too many open files
```

I increase the number of allowed open files with `ulimit -n 4096`, but then the client and server just "spam" open and close connections when trying to connect to the server.

```
2019/07/23 02:06:16 client: proxy#1:0.0.0.0:25567=>0.0.0.0:25567: conn#1001: Open
... omitted
2019/07/23 02:06:16 client: proxy#1:0.0.0.0:25567=>0.0.0.0:25567: conn#1250: Open
2019/07/23 02:06:16 client: proxy#1:0.0.0.0:25567=>0.0.0.0:25567: conn#1250: Close (sent 34B received 0B)
... omitted
2019/07/23 02:06:16 client: proxy#1:0.0.0.0:25567=>0.0.0.0:25567: conn#1001: Close (sent 34B received 0B)
```

Is this a bug in chisel? a limitation? or some protocol kink in Minecraft? I'm trying to get to the bottom of this, but it's difficult to figure out why this is happening. It would be great if chisel could work out-of-the-box with any TCP application, Minecraft included.

**Comment by jpillora** [comment]
Don't think it's a chisel limitation. It should use as much of the OS
resources as you'll let it. I guess you could test this by doing the same
thing with another TCP proxy seeing what happens?

**Comment by Electroid** [comment]
Works fine with https://github.com/mhzed/wstunnel.

```bash
# On the server:
wstunnel -s 0.0.0.0:25567

# On the client:
 wstunnel -t 25566:localhost:25565 ws://server-host:25567
```

**Comment by jpillora** [comment]
Oh interesting. So this only happens with a large number of concurrent
connections?

**Comment by Electroid** [comment]
Yes, it appears so.

**Comment by just1689** [comment]
Hello,

(I might be wrong about all of this)

It looks like your client is not telling the client to proxy : 25565 for you on the other side.

Could you try this:
`chisel client http://server-host localhost:25566:127.0.0.1:25565`

**Comment by jpillora** [comment]
Ah yes,

```
    --proxy, Specifies another HTTP server to proxy requests to when
    chisel receives a normal HTTP request. Useful for hiding chisel in
    plain sight.
```

Why are you using proxy?

**Comment by just1689** [comment]
@Electroid You ok? Can we close this one?

**Comment by Electroid** [comment]
Ah, thanks so much.
