### ISSUE TITLE
[Feature Request] Support client --authfile

### ISSUE THREAD

**Issue by netroby** [jpillora/chisel#11]
Dose chisel client support --authfile ?
I would prefer chisel read configure file from disk. and do not want other user view the password .

The current -auth put username and password on command line argument. when using ps -aux | grep chisel , you will see the password.
It might be not safe

**Comment by jpillora** [comment]
You can make a users.json file, see example dir

**Comment by netroby** [comment]
Sorry, i can not see --authfile argument for client.

https://github.com/jpillora/chisel/blob/master/client/client.go

there no --authfile read and parser

**Comment by jpillora** [comment]
Ah you're looking for an authfile on the client, not the server. Not implemented, though it wouldn't be too hard to add.

**Comment by jpillora** [comment]
`chisel client` now checks the `AUTH` env variable in `1.2.0`, so you can set `AUTH` in your service file. please update, see `chisel client --help`, test it out and let me know if there are any issues
