### ISSUE TITLE
Add docker support

### ISSUE THREAD

**Issue by netroby** [jpillora/chisel#12]
We can put chisel into docker image.
Here is my docker image

https://github.com/netroby/alpine-chisel
https://hub.docker.com/r/netroby/alpine-chisel/

and these guide how to using docker image

Both server and client need docker installed.

## Server side

There be a proxy server listen on 127.0.0.1:8123 on server. (squid or polipo)
create a file /etc/chisel.json, with content
```
{
	"USER:AVERYSTRONGPASSWORD": [
		""
	]
}
```
run command
```
docker run -d --restart=always --name chisel-server  -v /etc/chisel.json:/etc/chisel.json -p 0.0.0.0:8719:8719  netroby/alpine-chisel /bin/chisel server -v --port 8719 --authfile /etc/chisel.json
```

## Client side
$SERVER_IP will be your chisel server ip address
run command

```
docker run -d --restart=always --name chisel  -p 0.0.0.0:8123:8123  netroby/alpine-chisel /bin/chisel client -v --keepalive 300s --auth USER:AVERYSTRONGPASSWORD $SERVER_IP:8719 8123
```

After it success connected to chisel server, the localhost:8123 will forward tcp connection to remote server proxy server port. you will be access to the free network

**Comment by jpillora** [comment]
See https://github.com/jpillora/chisel#install, will put your guide up as a wiki page
