### ISSUE TITLE
NAT traversal scheme with chisel (help wanted)...

### ISSUE THREAD

**Issue by mikamiel** [jpillora/chisel#128]
Assume, I've got 3 machines (all in different locations):
1) http-server on Windows machine behind a NAT/firewall
2) http-client on Windows machine behind a NAT/firewall
Both computers(1 and 2) are controlled by me and are located in a different private subnets,
both of them can dial arbitrary tcp-connections to hosts located in the Internet,
NATs/firewalls are not controlled by me.
3) I've got Linux machine with a public IP, controlled by me.

Can I use chisel to create a sort of an encrypted TCP-port relay/proxy between machines 1 and 2 (with the help of 3rd machine)- so that http-client machine would be able to connect to tcp port of http-server machine?

As of now I use pure ssh-redirect solution but it has some drawbacks for me.

**Comment by vtolstov** [comment]
i need this too

**Comment by nguyentruongtho** [comment]
It should be fairly easy, you can run chisel server on your linux machine with reverse enabled. From (2), expose its port with reverse option and from (1), connect to the ports that exposed on the linux machine.

**Comment by mikamiel** [comment]
nguyentruongtho, thanks, I've tested it yesterday and it works.

- On Linux machine(3) with a public ip (203.0.113.203), start chisel in server mode on port 3333.
Its role here is a port-relay server, listening for client connections on port 3333.

`chisel server --port 3333 --reverse --auth user:Password`

- On http-server machine(1) that we want to securely share, start chisel in client mode.
It dials Linux machine(3) (ip 203.0.113.203, port 3333), authenticates, and tells to chisel server:
"i want to share my local TCP port 80 as a port 8888 on chisel server":

`chisel client --auth user:Password  203.0.113.203:3333  R:127.0.0.1:8888:127.0.0.1:80`

- On http-client machine(2) we want to establish a secure connection to http-server machine(1), bypassing its NAT. 
We start chisel here also in client mode.
It dials Linux machine(3) (ip 203.0.113.203, port 3333), authenticates, and tells to chisel server:
"i want to redirect your local TCP port 8888(on Linux machine(3)) to my local port 9999 (on http-client machine(2))":

`chisel client --auth user:Password  203.0.113.203:3333  127.0.0.1:9999:127.0.0.1:8888`

Now we can start browser on http-client machine(2) with  `127.0.0.1:9999`  in its address bar to make a secure connection to remote site on http-server machine(1).

**Comment by nguyentruongtho** [comment]
no problem, happy to help. You probably should close this issues.
