### ISSUE TITLE
Getting `accept4: too many open files` error 

### ISSUE THREAD

**Issue by ghissari** [jpillora/chisel#134]
I run the chisel with the bellow comment on the server and client:
_Server:_ `chisel  server -p 13002 --reverse`
_Client:_ `chisel client chisel.myserver.us:13002 R:0.0.0.0:13122:0.0.0.0:12430 `

After a week and transferring about 250Gb server stops working and I see this error in Syslog

**Server Log:**
`Feb  9 17:02:40 ubuntu bash[610]: 2020/02/09 17:02:40 server: proxy#1:R:0.0.0.0:13121=>0.0.0.0:12430: Listening
Feb  9 17:05:14 ubuntu bash[610]: 2020/02/09 17:05:14 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: Accept error: accept tcp4 0.0.0.0:13122: accept4: too many open files
Feb  9 17:05:14 ubuntu bash[610]: 2020/02/09 17:05:14 http: Accept error: accept tcp [::]:13002: accept4: too many open files; retrying in 5ms
Feb  9 17:05:14 ubuntu bash[610]: 2020/02/09 17:05:14 http: Accept error: accept tcp [::]:13002: accept4: too many open files; retrying in 10ms
Feb  9 17:05:14 ubuntu bash[610]: 2020/02/09 17:05:14 http: Accept error: accept tcp [::]:13002: accept4: too many open files; retrying in 20ms
Feb  9 17:05:14 ubuntu bash[610]: 2020/02/09 17:05:14 http: Accept error: accept tcp [::]:13002: accept4: too many open files; retrying in 40ms
Feb  9 17:05:14 ubuntu bash[610]: 2020/02/09 17:05:14 http: Accept error: accept tcp [::]:13002: accept4: too many open files; retrying in 80ms
Feb  9 17:05:40 ubuntu bash[610]: 2020/02/09 17:05:40 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: Listening
Feb  9 17:05:41 ubuntu bash[610]: 2020/02/09 17:05:41 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: Accept error: accept tcp4 0.0.0.0:13122: accept4: too many open files
Feb  9 17:19:38 ubuntu bash[610]: 2020/02/09 17:19:38 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: conn#271161: Stream error: ssh: unexpected packet in response to channel open: <nil>
Feb  9 17:19:38 ubuntu bash[610]: 2020/02/09 17:19:38 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: conn#270988: Stream error: ssh: unexpected packet in response to channel open: <nil>
Feb  9 17:19:38 ubuntu bash[610]: 2020/02/09 17:19:38 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: conn#270989: Stream error: ssh: unexpected packet in response to channel open: <nil>
Feb  9 17:19:38 ubuntu bash[610]: 2020/02/09 17:19:38 server: proxy#1:R:0.0.0.0:13122=>0.0.0.0:12430: conn#270990: Stream error: ssh: unexpected packet in response to channel open: <nil>
`

**Comment by jpillora** [comment]
https://github.com/jpillora/spy/blob/master/README.md#issues
