### ISSUE TITLE
How expose local website to internet

### ISSUE THREAD

**Issue by teopost** [jpillora/chisel#138]
Hi,
  I would like to expose my local web application (http://localhost: 8000/index.html) to internet address http://185.52.2.166:80/index.html.

I'm trying to use chisel to do it but I'm probably wrong in the configuration.

I ran chisel server on a cloud VM with public IP 185.52.2.166

**server**
```bash
[root@vm tmp]# chisel server --port 80
2020/03/19 15:58:44 server: Fingerprint a7:d9:a5:93:4d:86:d5:75:62:b4:72:93:b1:31:49:9f
2020/03/19 15:58:44 server: Listening on 0.0.0.0:80...
```

**client (my laptop)**
```bash
[root@mcbook tmp]#  ./chisel client http://185.52.2.166 8000
2020/03/19 17:00:58 client: Connecting to ws://185.52.2.166:80
2020/03/19 17:00:58 client: proxy#1:0.0.0.0:8000=>0.0.0.0:8000: Listening
2020/03/19 17:00:58 client: Fingerprint 8c:f6:15:9b:f8:c6:11:f0:8f:22:b4:dc:7c:d5:8c:af
2020/03/19 17:00:59 client: Connected (Latency 45.672614ms)
```

I wish my application was visible on the internet with address
http://185.52.2.166:80/index.html

It's possible to do it ?

**Comment by jpillora** [comment]
By default, chisel tunnels ports listening on the *client*, if you want to
tunnel ports listening on the *server* - you need to use --reverse. Note
with --reverse enabled, you must have more trust in your clients as they
can open any port on the server.

**Comment by teopost** [comment]
I added the server side -reverse option, but I'm still wrong
Can you give me an example?
![immagine](https://user-images.githubusercontent.com/2573389/77150971-4e9ffa80-6a95-11ea-8348-643891dc2c13.png)

![immagine](https://user-images.githubusercontent.com/2573389/77150988-565f9f00-6a95-11ea-8732-9f86a68683fb.png)

**Comment by jpillora** [comment]
See docs https://github.com/jpillora/chisel - Look under `chisel client --help`

**Comment by jpillora** [comment]
swap your `8000` argument for `R:8000` then visit the server's port 8000

**Comment by teopost** [comment]
Thank you.

**SERVER**

![immagine](https://user-images.githubusercontent.com/2573389/77153909-008df580-6a9b-11ea-8a71-b9447d805bec.png)

**CLIENT**

![immagine](https://user-images.githubusercontent.com/2573389/77153951-14395c00-6a9b-11ea-982c-ab83b46ec06f.png)

![immagine](https://user-images.githubusercontent.com/2573389/77153991-25826880-6a9b-11ea-92ad-c519a2276764.png)
 
Now It's work

![immagine](https://user-images.githubusercontent.com/2573389/77154029-3501b180-6a9b-11ea-824e-fabdad504842.png)

**Comment by jpillora** [comment]
👍

**Comment by marcosandresacevedo** [comment]
This post helped me achieve what I was trying to do. Thanks.
