### ISSUE TITLE
[::1]:53: read: connection refused on Android but works on pc

### ISSUE THREAD

**Issue by kawaiiDango** [jpillora/chisel#147]
I'm running a server on heroku using 
./chisel/chisel server --port $PORT --proxy http://example.com --socks5

./chisel client -v https://myapp.herokuapp.com/ 8888:socks
works fine on my pc, but on my Android 10 (arm64), I get the following and it keeps retrying:

```
2020/04/07 22:30:44 client: Connecting to wss://myapp.herokuapp.com:443/
2020/04/07 22:30:44 client: proxy#1:127.0.0.1:8888=>socks: Listening
2020/04/07 22:30:44 client: Connection error: dial tcp: lookup myapp.herokuapp.com on [::1]:53: read udp [::1]:47737->[::1]:53: read: connection refused
2020/04/07 22:30:44 client: Retrying in 100ms...
2020/04/07 22:30:44 client: Connection error: dial tcp: lookup myapp.herokuapp.com on [::1]:53: read udp [::1]:43560->[::1]:53: read: connection refused (Attempt: 1)
2020/04/07 22:30:44 client: Retrying in 200ms...
2020/04/07 22:30:44 client: Connection error: dial tcp: lookup myapp.herokuapp.com on [::1]:53: read udp [::1]:48258->[::1]:53: read: connection refused (Attempt: 2)
```

Also, no new requests show up in my heroku logs, so it didn't actually connect to the server.

**Comment by kawaiiDango** [comment]
I googled about this and this has something to do with the binary being compiled for linux arm and not android arm (they are different somehow). So I compiled it for android and it works.

I recommend adding android arm binaries to releases.

**Comment by jpillora** [comment]
Thanks for debugging, will add to goreleaser config

**Comment by jpillora** [comment]
Reverted the android release due to https://github.com/jpillora/chisel/runs/900081288?check_suite_focus=true If this is still needed. Please fix goreleaser config and re-open

**Comment by realyukii** [comment]
> I googled about this and this has something to do with the binary being compiled for linux arm and not android arm (they are different somehow). So I compiled it for android and it works.
> 
> I recommend adding android arm binaries to releases.

Can you tell me the instruction to build chisel for android?

**Comment by realyukii** [comment]
Fixed, turns out I just need to `export GOOS=android` and `go build`
