### ISSUE TITLE
Malware detected in chisel_1.4.0_windows_386.gz

### ISSUE THREAD

**Issue by LaG1924** [jpillora/chisel#157]
Windows Defender just detected `Trojan:Win32/Wacatac.C!ml` in .gz archive, and marks unpacked .exe from it as suspicious.
![image](https://user-images.githubusercontent.com/12997935/80856851-f1d45a00-8c66-11ea-8aed-989f2ae3626a.png)

Looks like problem in .gz container, because packed executable detected more frequent.
[VirusTotal scan for chisel_1.4.0_windows_386.gz](https://www.virustotal.com/gui/file/70ddb33c1ce8b8ac5d3a7339ed37fedf436f91e5a31bdd19c8029968766ad3e6/detection)
[VirusTotal scan for chisel.exe](https://www.virustotal.com/gui/file/53e53dafe3285c4752bc75c8a18e3cdc0fbe6bc7437105468da76f9c3ee886f2/detection)
UPD: I forced rescan of chisel.exe and it became much more malware than 8 days ago... So, problem in chisel.exe, not in archive.

**Comment by jpillora** [comment]
Strange, tried compiling from source?

**Comment by LaG1924** [comment]
Installed golang-compiler, executed `go get -v github.com/jpillora/chisel`. Malware is not detected in executable.  Only minor strange thing is `Version: 0.0.0-src`.
[VirusTotal detection: 1/70](https://www.virustotal.com/gui/file/2e8d1cab6499a57a9ac70a50975116051c0c3fc4c3b41bdcbfe7efa9a29e42ca/detection)

Is problem in uploaded asset to github?

**Comment by LaG1924** [comment]
Ok, I compiled it for x86. It keeps detecting malware, but not so tragic as for your precompiled version.
[VirusTotal for x86: 7/70](https://www.virustotal.com/gui/file/17179833ead8a6060d313c7b4e5d41387cc553168611036f283d00b8142a1e0c/detection)

**Comment by jpillora** [comment]
Okay since you can reproduce, I’m going to say this is a bug with your AV
