### ISSUE TITLE
Use Gorilla UnderlyingConn?

### ISSUE THREAD

**Issue by rishabh-arya95** [jpillora/chisel#159]
Hi there, just a question I can see you have created a function NewWebSocketConn]https://github.com/jpillora/chisel/blob/d9c45c6b902273097c017d8ba843ddf9c4abd2bc/share/conn_ws.go#L16 which basically return the net.Conn for the websocket connection,  I can see you are  using the gorilla websocket library, so why you have not used gorilla websocket [UnderlyingConn](https://pkg.go.dev/github.com/gorilla/websocket?tab=doc#Conn.UnderlyingConn) which seems to do the same thing ? Were there any issues with it or are these both different ?

**Comment by jpillora** [comment]
Doing this will result in invalid websocket traffic. So it might work in some cases, though if proxies are reading websocket messages, they'll fail. Overhead should be small, though happy for you re-open to post some benchmarks here of using both
