### ISSUE TITLE
Issue when launching in Windows 10

### ISSUE THREAD

**Issue by jasonnm** [jpillora/chisel#161]
I downloaded the Windows AMD64 binary and unzipped - when I try to run it, a window pops up and disappears again instantly. It's so fast I can't even see what is in the window.
I checked in the Event Viewer and found nothing - is there a separate log somewhere, so I can see what's happening?
Is there something I'm missing?

Update: I also installed Go, downloaded source and built locally, and I still have the same issue.

**Comment by jpillora** [comment]
Run it with cmd to see the message

**Comment by jasonnm** [comment]
Got it! Sorry - I tried everything BUT that... got it working now - thanks very much.
