### ISSUE TITLE
Port Mapping

### ISSUE THREAD

**Issue by gvsurenderreddy** [jpillora/chisel#162]
Hello sir 
Is port mapping possible using Chisel local host 2222 to Remote 22

**Comment by patrick-othmer** [comment]
Sure

Local port on chisel server will be 22
```
chisel client your.chisel.server R:22:localhost:2222
```

**Comment by gvsurenderreddy** [comment]
Sir but that Port should be empty let says SSHD is working on 22 on server then it will not work . I want it work even when Port 22 is in use so I can use Localhost 2222 to connect to server Is this possible please.

**Comment by jpillora** [comment]
`chisel client <server-ip> 2222:<target-ip>:22`
