### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by jcoetzee** [jpillora/chisel#17]
I'm trying to get started with chisel by running the demo but I can't get client to connect.
> ~> docker run --rm -it jpillora/chisel client https://chisel-demo.herokuapp.com 3000
> 2016/06/28 10:15:58 client: Connecting to wss://chisel-demo.herokuapp.com:443
> 2016/06/28 10:15:59 client: Retrying in 100ms...
> 2016/06/28 10:16:00 client: Retrying in 200ms...
> 2016/06/28 10:16:01 client: Retrying in 400ms...
> 2016/06/28 10:16:02 client: Retrying in 800ms...
> 2016/06/28 10:16:04 client: Retrying in 1.6s...
> 2016/06/28 10:16:06 client: Retrying in 3.2s...

I can browse to the webpage in browser and get example.com output however.

**Comment by jpillora** [comment]
Seems to be up for me

```
$ chisel client --keepalive 30s https://chisel-demo.herokuapp.com 4300:3000
2016/06/30 13:26:50 client: Connecting to wss://chisel-demo.herokuapp.com:443
2016/06/30 13:26:52 client: Fingerprint 66:0c:73:a3:4d:5f:ef:e4:1d:aa:b1:15:1a:2d:2d:5e
2016/06/30 13:26:53 client: Connected (Latency 280.462653ms)
```
