### ISSUE TITLE
Authfile watcher remove credentials

### ISSUE THREAD

**Issue by scriptcoded** [jpillora/chisel#171]
If the server is started with an authfile and a credential pair is completely removed from the file it won't be invalidated by the application.

### Steps to reproduce

1. Start the server with the following `users.json` file:
```json
{
  "foo:bar": [""],
  "root:toor": [""]
}
```
```bash
chisel server --authfile ./users.json
```
2. Remove the credentials from `users.json`:
```json
{
  "foo:bar": [""]
}
```
3. Try authenticating with the client:
```bash
chisel client --auth root:toor example.com:8080 3000
```

4. Observe how the client is successfully authenticated

**Comment by jpillora** [comment]
This should be resolved in `v1.7.0-rc5`, can test it there. Will release as `v1.7.0` soon hopefully

**Comment by scriptcoded** [comment]
@jpillora I'll make sure to check it out before tomorrow!

**Comment by jpillora** [comment]
Will close, but feel free to reopen if still an issue

**Comment by scriptcoded** [comment]
@jpillora Sorry. Totally forgot to check it out. I'll do if I get the time.
