### ISSUE TITLE
v1.7.0-rc3 fails to show when connected on server side (Reverse tunnel)

### ISSUE THREAD

**Issue by asheroto** [jpillora/chisel#173]
I have a reverse tunnel set up.  Chisel does connect, but on the server side it just continues to show "Listening on...." and never says "connected on port xxx" or "disconnected".  I tested it and the tunnel itself does work, it just doesn't say connected or what port number on the server.

This is on version v1.7.0-rc3.

**Comment by jpillora** [comment]
Ah yeah I changed the logging, you can enable --verbose for now though I
should revert to show the previously shown logs

**Comment by jpillora** [comment]
Resolved in `v1.7.0-rc5`
