### ISSUE TITLE
Set users

### ISSUE THREAD

**Issue by scriptcoded** [jpillora/chisel#175]
Hey!

I'm not 100% sure if the exposed API is supported, but right now there are two methods for interacting with users; `AddUser` and `DeleteUser`. I have a use case where I have a different source of users, and it would be of much use to be able to have something like `SetUsers` to override the whole user map. If it's something that you think might fit in I'd be happy to submit a PR.

Proposed API:

```go
// Same as used right now
type User struct {
  Name  string
  Pass  string
  Addrs []*regexp.Regexp
}

// ...

server.SetUsers([]User{
  {
    "foo",
    "bar",
    []*regexp.Regexp{regexp.MustCompile("^0.0.0.0:3000$")},
  },
  {
    "root",
    "toor",
    []*regexp.Regexp{regexp.MustCompile("")},
  },
})
```

**Comment by jpillora** [comment]
Added `Server` method `ResetUsers(users)` in `v1.7.0-rc4` 👍
