### ISSUE TITLE
is there keepalive for server?

### ISSUE THREAD

**Issue by ezbik** [jpillora/chisel#176]
is there keepalive for server? It is needed to free `R` forwarded ports when there is a network outage between a client & the server.
Main Github page states there is keepalive for Chisel server, but `chisel server -h` is not showin it.

```
#  /usr/local/bin/chisel_linux_amd64  server  -h | grep keepalive
# 

#  /usr/local/bin/chisel_linux_amd64  server  -h | grep Vers -A1
  Version:
    1.6.0 (go1.14.4)
```

**Comment by jpillora** [comment]
There is in the release candidate version 1.7.x

**Comment by ezbik** [comment]
Thank you @jpillora , it was my fault.
