### ISSUE TITLE
Server - detect disconnected clients & free up their ports

### ISSUE THREAD

**Issue by ezbik** [jpillora/chisel#177]
Remotely forwarded ports should be released when a client is considered offline.
The way to reproduce:

Server

```
chisel_linux_amd64  server -p 8082  --reverse --keepalive 5s --authfile $CHISEL_SERVER_AUTH_FILE  -v  
```

Client:

```
chisel_linux_amd64 client --auth x:y -v Chisel_server:8082 R:0.0.0.0:8142:localhost:8142
```

( gets connected, local port 8142 gets exposed to chisel server, all good..)
Simulate network outage on client by blocking outgoing port 8082 where chisel server is listening to. Client starts to retry connection. 
Kill the client.
Unblock the port.
Rerun chisel client, it will show:

```
2020/07/29 20:16:27 client: Connection error: server: Remote R:8142=>localhost:8142 cannot listen
```

And that port is held **for 1 minute 30 seconds** on Chisel server side until Chisel server releases it. So the client can't reconnect.

**Possible solution:**

Implement something like ClientAliveInterval & ClientAliveCountMax as they are in SSH server. So offline clients & their ports are released more quickly e.g. within 3s.

**Comment by jpillora** [comment]
Interesting, I assumed that binding the request context (should include the
client tcp connection)
https://github.com/jpillora/chisel/blob/master/server/server_handler.go#L146
would
kill all resources related to the client. Will test soon

**Comment by jpillora** [comment]
We do need to speed up the keep alive timeout, however i think the better solution here is detect the same remotes from the same chisel client (public key) on the second connection and force drop the first connection

**Comment by jpillora** [comment]
Can you please test the latest `1.7.0-rc` ?

**Comment by ezbik** [comment]
Tested 1.7.0-rc9 , the bug disappeared.
When firewall is open (after being blocked), client says during its first run:

`2020/09/05 23:18:13 client: Connection error: server: Server cannot listen on R:2222=>localhost:22`

.. and quits immediately.

On its 2nd run it forwards ports properly.

Thank you!

**Comment by jpillora** [comment]
Good to hear
