### ISSUE TITLE
Panic: multiple getters

### ISSUE THREAD

**Issue by OneHappyForever** [jpillora/chisel#179]
It seems that when there are clients constantly trying to connect through the tunnel while the tunnel is starting, the tunnel can't connect successfully, perhaps because of an overload?

I tried using a different port that wasn't being actively connected to and it starts successfully.

Client side:
2020/08/03 05:13:57 client: tun: proxy#205=>2080: Listening
2020/08/03 05:13:57 client: tun: proxy#205=>2080/udp: Listening
2020/08/03 05:13:57 client: tun: Bound proxies
2020/08/03 05:13:57 client: tun: proxy#205=>2080: conn#1: Open
panic: multiple getters

goroutine 49 [running]:
github.com/jpillora/chisel/share/tunnel.(*Tunnel).getSSH(0xc00001e840, 0x9dcac0, 0xc0000f61c0, 0x0, 0x0)
        github.com/jpillora/chisel/share/tunnel/tunnel.go:128 +0x39d
github.com/jpillora/chisel/share/tunnel.(*Proxy).pipeRemote(0xc000085540, 0x9dcac0, 0xc0000f61c0, 0x7fd9b78cb008, 0xc000286000)
        github.com/jpillora/chisel/share/tunnel/tunnel_in_proxy.go:128 +0x168
created by github.com/jpillora/chisel/share/tunnel.(*Proxy).runTCP
        github.com/jpillora/chisel/share/tunnel/tunnel_in_proxy.go:118 +0xe1

-----

Server side:

2020/08/03 17:13:10 server: session#7: Handshaking...
2020/08/03 17:13:11 server: Failed to handshake (websocket: close 1006 (abnormal closure): unexpected EOF)

Anything that can be done?

-----

Edit:

Here's my commands:

./chisel server -p 80 -v
./chisel client -v website.com:80 205:2080 205:2080/udp

**Comment by jpillora** [comment]
Thanks for the report, I’ll look into it

**Comment by ezbik** [comment]
The same is on my side.

Client :

```
2020/08/11 11:41:05 client: Connecting to ws://x.x.x.x.x:xxxx
2020/08/11 11:41:05 client: tun: proxy#16000=>socks: Listening
2020/08/11 11:41:05 client: tun: Bound proxies
2020/08/11 11:41:05 client: tun: proxy#16000=>socks: conn#1: Open
2020/08/11 11:41:05 client: tun: proxy#16000=>socks: conn#2: Open
panic: multiple getters

goroutine 34 [running]:
github.com/jpillora/chisel/share/tunnel.(*Tunnel).getSSH(0xc000098780, 0x9ddfc0, 0xc00013a240, 0x0, 0x0)
	github.com/jpillora/chisel/share/tunnel/tunnel.go:128 +0x39d
github.com/jpillora/chisel/share/tunnel.(*Proxy).pipeRemote(0xc0000c7400, 0x9ddfc0, 0xc00013a240, 0x7f55b9ceb008, 0xc000182008)
	github.com/jpillora/chisel/share/tunnel/tunnel_in_proxy.go:128 +0x168
created by github.com/jpillora/chisel/share/tunnel.(*Proxy).runTCP
	github.com/jpillora/chisel/share/tunnel/tunnel_in_proxy.go:118 +0xe1
```

**Comment by jpillora** [comment]
Found the bug, haven’t had a chance to test the fix yet - will aim for
tonight
