### ISSUE TITLE
Usage Help: Multiple Hops

### ISSUE THREAD

**Issue by sharanga7** [jpillora/chisel#182]
Lets say there are four entities. clientA, serverB, serverC, serverD
serverD can only be accessed from serverC
serverC can only be accessed from serverB.
serverB is accessible to clientA.

How should I run chisel on all the three entities - clientA, serverB and serverC so that I can hit serverD endpoint from clientA.

**Comment by jpillora** [comment]
Chisel is point to point. This can work, but you'd need to run multiple chisel processes on `C`.

Say you want to connect to port 80 on `D`
`C` connects to `D` opening remote `80:80`
`B` connects to `C` opening remote `80:80`
`A` connects to `B:80` and will end up at `D:80`

**Comment by jpillora** [comment]
*Edited above*
