### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bgaff** [jpillora/chisel#19]
Hi, this is a really neat project you've hacked together. Just out of curiosity, if you're controlling clients and servers on both ends why don't you just tunnel tcp via a tls channel and be done with it? Why do you need HTTP in there at all?

**Comment by bgaff** [comment]
I forgot to mention if it's a TLS tunnel on port 443 you get the same result without the application layer overhead of http.

**Comment by jpillora** [comment]
True, it would work with TCP, I added HTTP and WebSockets to get through
HTTP Proxies/Firewalls. Specifically, I wanted to put it on Heroku, which
must go through their HTTP proxy/router.

**Comment by bgaff** [comment]
Oh I see, they are terminating TLS for you in front of your frontend server, I assumed it was TLS all the way to your frontend. Thanks for the clarification!
