### ISSUE TITLE
1.7.0-rc9 out and err streams are mixed up

### ISSUE THREAD

**Issue by nosf3rat** [jpillora/chisel#191]
Hello!

I tried 1.7.0-rc9 version cause of TLS ignore feature (that is important for me, thanx for it!)
And I noticed that out and err streams are mixed up on win 10
I tired with the next command:

```
chisel client -v --tls-skip-verify --auth test:test https://my-test.host.local 127.0.0.1:2222:127.0.0.1:3333 1> d:\out.txt 2> d:\err.txt
```

**Comment by jpillora** [comment]
What does  mixed up mean in this case? Can you paste in the contents of the
files?

**Comment by nosf3rat** [comment]
Of course

out.txt is empty

err.txt is next:
```
2020/09/08 19:46:01 client: TLS verification disabled
2020/09/08 19:46:01 client: Connecting to wss://my-test.host.local:443
2020/09/08 19:46:01 client: tun: proxy#127.0.0.1:2222=>3333: Listening
2020/09/08 19:46:01 client: tun: Bound proxies
2020/09/08 19:46:01 client: Handshaking...
2020/09/08 19:46:01 client: Fingerprint fe:24:f3:f5:a7:50:05:c1:a3:ba:c0:bb:f2:bc:69:b7
2020/09/08 19:46:01 client: Sending config
2020/09/08 19:46:01 client: Connected (Latency 1.4968ms)
2020/09/08 19:46:01 client: tun: SSH connected
```

**Comment by jpillora** [comment]
Ah this is intentional, chisel client can be in stdio mode, where stdin and
stdout are used as data input/output

**Comment by nosf3rat** [comment]
So it is expected and final behaviour?
For me it was strange to see normal output in error stream - and may be unexpected by some users
But if it is expected and is not a bug - OK, I'll just close issue

**Comment by jpillora** [comment]
https://golang.org/pkg/log/

> Package log implements a simple logging package. It defines a type, Logger, with methods for formatting output. It also has a predefined 'standard' Logger accessible through helper functions Print[f|ln], Fatal[f|ln], and Panic[f|ln], which are easier to use than creating a Logger manually. That logger writes to **standard error** and prints the date and time of each logged message. Every log message is output on a separate line: if the message being printed does not end in a newline, the logger will add one. The Fatal functions call os.Exit(1) after writing the log message. The Panic functions call panic after writing the log message.

By default, Go's standard library logging package logs to stderr, so I figured this was a safe choice. If there was a strong argument, I would consider using stdout when not in stdio mode?

**Comment by nosf3rat** [comment]
That's not necessary for me
Thanx for explanation!
