### ISSUE TITLE
ctx must be set

### ISSUE THREAD

**Issue by scriptcoded** [jpillora/chisel#195]
There is no documented way to use this library with go directly, but I'll submit my issue here anyways.

When running like this (stipped down), the library returns from `Run` with the error `ctx must be set`.

```go
s, err := chserver.NewServer(&chserver.Config{
  Reverse: true,
})
if err != nil {
  log.Fatal(err)
}

if err := t.Server.Run("0.0.0.0", "8080"); err != nil {
  log.Fatal(err)
}
```

This is due to the following lines

https://github.com/jpillora/chisel/blob/master/share/cnet/http_server.go#L46-L48

Which in turn means that both `Server.Run` and `Server.Start` are broken since they don't provide a context.

**Comment by jpillora** [comment]
Thanks for the report. This is a bug. I added more context in for 1.7.0 and forgot to come back to this! I'll try to take a look soon. There's now a `StartContext`, and for backwards compatibility, `Start` (`Run`) should just default to use a background context

**Comment by scriptcoded** [comment]
@jpillora Yup, I am using `StartContext` now. Is the Go API officially supported anyways? If not, don't prioritize this for the sake of my usage :)

**Comment by jpillora** [comment]
It is supported, though it’s why 1.7.0 is still in RC, wanting to iron out
any bugs with the API before I tag v1.7.0. Hopefully will get this fixed
soon
