### ISSUE TITLE
Module version in Go package

### ISSUE THREAD

**Issue by scriptcoded** [jpillora/chisel#196]
This is not a bug nor an issue, but perhaps rather an improvement.

When using the package with Go, the version is set to the default `0.0.0-dev`. This makes sense as the published version is injected at build time. It does, however, cause quite a few unnecessary logs like the following:

```
Client version (1.6.0) differs from server version (0.0.0-src)
```

I would consider this to be the expected behavior, though if this module is supposed to be usable by third parties the warning might cause unnecessary confusion, and perhaps even break something that I'm not aware of.

If the protocol version is the only thing that's actually breaking, perhaps an option to suppress the warning would be an easy fix. Though that kind of defeats the meaning of the warning in the first place.

Keep up the good work! I've been making good use of this module, and the clean and open API makes everything a breeze to use. :tada:

**Comment by jpillora** [comment]
Good point, I think suppressing the warning (when unset) is all we can do.
Thanks :)

**Comment by scriptcoded** [comment]
Sound fair! :)
