### ISSUE TITLE
IPv6 remotes?

### ISSUE THREAD

**Issue by shawnhwei** [jpillora/chisel#197]
Seems like the chisel client doesn't like ipv6 remote addresses (e.g. [::1]:8888).

Based on [here](https://github.com/jpillora/chisel/blob/6fce8e1e6e3bf2da6f32eaaaab692022137319d0/share/settings/remote.go#L49) I'm guessing this is to be expected.

Or maybe I'm doing it wrong?

**Comment by jpillora** [comment]
True, v6 should be supported, so this is a bug. PR? Otherwise I’ll work on
it when I get a chance next
