### ISSUE TITLE
[Feature Request] Add support for an http proxy

### ISSUE THREAD

**Issue by nonoderclown** [jpillora/chisel#2]
Thanks for all your work !
I use Chisel Client in Windows 7. Internet connection of our company runs through a proxy.
Chisel Client does not seem to support a http proxy (I tried to set HTTP_PROXY in ENV).
Did I miss a point ? Do you see a possibility to get it working ?

**Comment by jpillora** [comment]
No, you are correct, chisel does not yet support a http proxy. I have not
looked into this yet though I know it definitely could work however I
believe it could be complicated by the fact chisel relies on WebSockets,
needs some research

**Comment by chromicant** [comment]
I've got a version working with an HTTP proxy. My setup is a bit odd, so the code may be a bit hackish. It works with a HTTP proxy on the client side, and the chisel  server is behind a NGINX server.

Code is in #14
