### ISSUE TITLE
Binary Installation Issue on Ubuntu

### ISSUE THREAD

**Issue by wh1t3-n01s3** [jpillora/chisel#20]
On Ubuntu 16.04 there appears to be a conflict when installing via dpkg -i <path>.  The binary tries to install a file named test under /usr/bin but /usr/bin/test already exists as part of coreutils.  Perhaps renaming to something more descriptive (and unique) would be better.

**Comment by jpillora** [comment]
The `.deb` releases were made by now-unsupported tool. Replacing `/usr/bin/test` is bad so I think I'll just remove all deb releases. I just released `1.1.4` https://github.com/jpillora/chisel/releases download the linux amd64 binary and place it in `/usr/local/bin/chisel` and make it executable

Or you can use `curl https://i.jpillora.com/chisel! | bash` which does this
