### ISSUE TITLE
Slow/stuttery upload speeds on 1.7.1

### ISSUE THREAD

**Issue by astravexton** [jpillora/chisel#200]
I downloaded version 1.7.1 of the binary for linux on both my local pc and server, server side was run as `chisel server --auth some:auth -p 27501` and on the client side `chisel client --auth some:auth --hostname hostna.me <server ip>:80 1194`. I have OpenVPN running on the server and tested both UDP and TCP with 1.7.1 and found out that my upload speed was stuttering quite a lot and limited to around 1Mbps, but when I downgraded chisel to 1.6.0 my upload speed went back up to around 4Mbps and wasn't stuttering at all. I'm not sure what changed between 1.6.0 and 1.7.1 (except for UDP), but something had broken the TCP upload speed

**Comment by jpillora** [comment]
Interesting, TCP throughput shouldn’t have changed - this is most likely a
bug. Can you share some more info: what’s the latency difference between
the two endpoints?  Is  UDP and TCP bandwidth the same? How are you running
the test?

This might be related to the websocket buffer size change...

**Comment by astravexton** [comment]
Latency is around 40-50ms on 1.7.1 using either TCP or UDP, also the same on 1.6.0. TCP and UDP upload bandwidth on 1.7.1 are both the same (around 1Mbps on speedtest.net but very stuttery), and TCP on 1.6.0 is around 4Mbps. Weirdly my download speed is fine on either version and TCP or UDP, just my upload that seems to have issues

**Comment by jpillora** [comment]
I just did some testing with my macbook and a linux server, connected over a Google Wifi router (these results represent the average run).

mac server, linux client:

```
# linux -> mac (no chisel)
$ iperf -c 192.168.86.25
------------------------------------------------------------
Client connecting to 192.168.86.25, TCP port 5001
TCP window size: 85.0 KByte (default)
------------------------------------------------------------
[  3] local 192.168.86.50 port 51738 connected with 192.168.86.25 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   602 MBytes   503 Mbits/sec

# linux (with chisel client 192.168.86.25:8080 5001) -> mac (with chisel server)
$ iperf -c localhost
------------------------------------------------------------
Client connecting to localhost, TCP port 5001
TCP window size: 3.51 MByte (default)
------------------------------------------------------------
[  3] local 127.0.0.1 port 44860 connected with 127.0.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  3]  0.0-10.0 sec   563 MBytes   471 Mbits/sec
```

linux server, mac client:

```
# mac -> linux (no chisel)
$ iperf -c 192.168.86.50
------------------------------------------------------------
Client connecting to 192.168.86.50, TCP port 5001
TCP window size:  129 KByte (default)
------------------------------------------------------------
[  4] local 192.168.86.25 port 50250 connected with 192.168.86.50 port 5001
[ ID] Interval       Transfer     Bandwidth
[  4]  0.0-10.0 sec   394 MBytes   330 Mbits/sec

# mac (with chisel client 192.168.86.50:8080 5001) -> linux (with chisel server)
$ iperf -c localhost
------------------------------------------------------------
Client connecting to localhost, TCP port 5001
TCP window size:  144 KByte (default)
------------------------------------------------------------
[  5] local 127.0.0.1 port 50778 connected with 127.0.0.1 port 5001
[ ID] Interval       Transfer     Bandwidth
[  5]  0.0-10.0 sec   398 MBytes   334 Mbits/sec
```

So I do see different speeds to/from each machine, but the difference doesn't seem to be coming from chisel in my case.

Are you able to reproduce this in a test?
