### ISSUE TITLE
null pointer dereference

### ISSUE THREAD

**Issue by ffcommax** [jpillora/chisel#206]
null pointer dereference when port in use with other program

python -m SimpleHTTPServer 8080
Serving HTTP on 0.0.0.0 port 8080 ...

`./chisel_1.7.2_linux_amd64 server
2020/10/24 16:21:03 server: Fingerprint 35:b6:0a:dc:24:60:8b:79:34:5a:15:17:b3:87:f1:bb
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x70bb6d]

goroutine 8 [running]:
net/http.(*onceCloseListener).close(...)
        net/http/server.go:3371
sync.(*Once).doSlow(0xc0000f2550, 0xc000070c00)
        sync/once.go:66 +0xec
sync.(*Once).Do(...)
        sync/once.go:57
net/http.(*onceCloseListener).Close(0xc0000f2540, 0x0, 0x0)
        net/http/server.go:3367 +0x78
panic(0x8aaf20, 0xc3d840)
        runtime/panic.go:969 +0x175
net/http.(*onceCloseListener).Accept(0xc0000f2540, 0xc000022078, 0x8a0ae0, 0xc3d780, 0x918fc0)
        <autogenerated>:1 +0x32
net/http.(*Server).Serve(0xc0000ce1c0, 0x0, 0x0, 0x0, 0x0)
        net/http/server.go:2937 +0x266
github.com/jpillora/chisel/share/cnet.(*HTTPServer).GoServe.func1(0x0, 0x0)
        github.com/jpillora/chisel/share/cnet/http_server.go:53 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0000f24e0, 0xc00000d8e0)
        golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66
`

**Comment by jpillora** [comment]
Thanks for the report!

**Comment by jpillora** [comment]
Fixed in https://github.com/jpillora/chisel/commit/87675c40bc9ad5bfb5d751aed4ed1889ad85a841
