### ISSUE TITLE
Kaspersky Anti-virus treats chisel as threat

### ISSUE THREAD

**Issue by nosf3rat** [jpillora/chisel#209]
Hello!

After 1.7.0+ version Kaspersky Anti-virus begins to treat chisel as threat on Windows:

```
02.11.2020 10:47:08	Found legal software that may be used by criminals to damage your computer or personal data.	File Threat Protection	Windows Command Processor	<username>	Found: HEUR:HackTool.Win32.Chisel.a	D:\Download\chisel\chisel.exe	Expert analysis	0	1604291340	0
```

Anti-virus immediately moves chisel to internal quarantine after unzipping

This behaviour does not reproduce on 1.6.0 and lower

**Comment by jpillora** [comment]
Well the message is correct, it can be used to exfil data, but not on its
own - it needs some other tool/script driving it. Does this reproduce if
you compile the exe from source? I'm guessing the released binary's hash
has been added to some database....

**Comment by dedo1911** [comment]
It's doing some sort of heuristic match I think, I'm having the same issue in my application with chisel embedded in it.

**Comment by jpillora** [comment]
If you pull out the socks  library, does it still match? What if you change
symbol names?

**Comment by dedo1911** [comment]
How do I do that?

**Comment by jpillora** [comment]
comment out the use of the socks library, and edit the code so it still compiles, though this might take a bit of trial and error to find exactly what its flagging

sorry I can't help more, I don't have a windows machine
