### ISSUE TITLE
User authentication problem

### ISSUE THREAD

**Issue by kevinalbarton** [jpillora/chisel#212]
I think there is a bug with chisel authentication:
I have ran chisel server with users.json file like below:

users.json:

```
{
  "kevin:12345": [
      ""
  ]
}
```

server side command:

`chisel.exe  server --authfile "C:\Users\kevin\Desktop\users.json" --port 8090 --reverse --socks5`

and output:

```
2020/11/07 20:37:19 server: Reverse tunnelling enabled
2020/11/07 20:37:19 server: Fingerprint f2:ec:76:82:f8:83:5f:d3:10:cb:04:cc:a6:0d:85:d8
2020/11/07 20:37:19 server: User authenication enabled
2020/11/07 20:37:19 server: Listening on http://0.0.0.0:8090
```

But when I run following command on clientside:

`chisel.exe client 192.168.5.43:8090 --auth kevin:12345 socks`

or

`chisel.exe client 192.168.5.43:8090 --auth "kevin:12345" socks`

I receive:

`2020/11/08 11:36:55 Failed to decode remote '--auth': Missing ports`

I don't know if my client side command is not in the right format or there is a bug in the chisel.
Everything was OK without authentication so I concluded only authentication is the focus point for error.

**Comment by vetch101** [comment]
Hi,

You need the --auth option before the remote target vs after it.

Try:

`chisel client --auth "xxx:yyy" 192.168.5.43:8090 socks
`

**Comment by kevinalbarton** [comment]
Thanks, resolved
