### ISSUE TITLE
Reverse Proxy for local RTSP IP Camera

### ISSUE THREAD

**Issue by cedricve** [jpillora/chisel#216]
Hello @jpillora 

Great work here! I'm trying to reverse proxy an internal IP camera (:554 RTSP/TCP), and actuallly it works ;)

The only thing I noticed is that there is a huge lag (frames should be send 30FPS 1280x720 resolution), but only a few come in at a time. Is this due to encryption? 

Anything that comes up into your mindd?

**Comment by cedricve** [comment]
this was caused due to my bad internal network and bandwidth.

**Comment by tri-bao** [comment]
hi @cedricve 
I'd like to do the same but couldn't be able to make it happen. what chisel command arguments that you used at the chisel server and at the chisel client?

I have a "server" node which runs chisel server, a "client" node which runs chisel client and an IP camera which stays in the same network as the client node.
