### ISSUE TITLE
How to Create a communication Tunnel

### ISSUE THREAD

**Issue by cedricve** [jpillora/chisel#217]
Hey there, so cool this library (thankss @jpillora), I'm looking into the code and would like to understand more. 

I understand that a single tunnel is created from client to server, and that at start all the remotes are passed from client to server. Afterwards (if reversed) all ports are opened on server side, and each one of them is tunneled through the one and only TCP connection.

I'm just wondering how, and if, this tunnel can also be used for other bi-directional communication. For example using it for the reverse tunneling, but at the same time use (the same tunnel) it as a communication protocol (like what we do with websockets).

Any tips or tricks might be useful, and would also be great to document this.

**Comment by cedricve** [comment]
After analyzing the source code, I came to the conclusion that there are ssh request being send for setting up the handshake. Afterwards I also found out the keepalive function which is periodically sending pings to the server.

What I am aiming for is to have an easy way to specific a communication function. I have seen you here already processes the requests: 

But on the client you there is nothing available. I ended up extending the `client_connect`function, and do something like this. So endless for loop, continiously listening for requests with a time out and then a switch case for replying.

		go func() {
			for {
				var r *ssh.Request
				select {
					case r = <-reqs:
					case <-time.After(10*time.Second):
						fmt.Println("Timeout waiting for message")
				}
				
				// case if ..
				if r != nil {
					if r.Type == "ping" {
						fmt.Println("Received a ping, sending a heartbeat.")
						_, _, err := sshConn.SendRequest("heartbeat", true, nil)
						if err != nil {
							break
						}
					}
					r.Reply(true, nil)
				}
			}
			return
		}()

On the server side I extended this function.


		func (t *Tunnel) handleSSHRequests(reqs <-chan *ssh.Request) {
			for r := range reqs {
				switch r.Type {
				case "ping":
					r.Reply(true, []byte("pong"))
				case "heartbeat":
					fmt.Println("received heartbeat")
					r.Reply(true, []byte("beat"))
				default:
					t.Debugf("Unknown request: %s", r.Type)
				}
			}
		}


Any thoughts @jpillora to make this more configurable? I believe this makes a lot of sense, especially when you want to extend your beautiful work with custom business logic.

**Comment by cedricve** [comment]
Started working on this myself. Forked the repo, but not sure this will ever come into this repo. As activity looks low.

**Comment by smanghate** [comment]
@cedricve - I have same use case. above mentioned repo is not accessible.

**Comment by smanghate** [comment]
@cedricve not able to access your chisel repo. was it feasible to implement communication tunnel with chisel?
