### ISSUE TITLE
Server reverse mode, cannot reconnect when agent network disconnects

### ISSUE THREAD

**Issue by cedricve** [jpillora/chisel#218]
It looks like when running in reverse proxy mode, the port stays open on the server when a client abruptly disconnects (network change). When restarting the server, it can connect again. This is ofcourse not what you want do in production.

     2020/11/18 20:40:55 client: Connecting to ws://104.155.68.201:8000
     2020/11/18 20:40:56 client: Fingerprint xItxPXkfNwvTMcCl6Mgzd+SgRQVC2eLu7bTG8bxRywI=
     2020/11/18 20:40:57 client: Connection error: server: Server cannot listen on R:52081=>192.168.0.78:554
     2020/11/18 20:40:57 client: Give up

**Comment by jpillora** [comment]
What do the server logs contain at the time of the client disconnection?

**Comment by cedricve** [comment]
2020/11/18 18:55:51 server: session#6: Handshaking...
2020/11/18 18:55:51 server: session#6: Verifying configuration
2020/11/18 18:55:51 server: session#6: tun: Created
2020/11/18 18:55:51 server: session#6: tun: proxy#R:52081=>192.168.0.78:554: Listening
2020/11/18 18:55:51 server: session#6: tun: proxy#R:51318=>192.168.0.153:554: Listening
2020/11/18 18:55:51 server: session#6: tun: proxy#R:44425=>192.168.0.79:554: Listening
2020/11/18 18:55:51 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: Listening
2020/11/18 18:55:51 server: session#6: tun: Bound proxies
2020/11/18 18:55:51 server: session#6: tun: SSH connected
2020/11/18 18:55:56 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#1: Open
2020/11/18 18:55:56 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#2: Open
2020/11/18 18:55:56 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#2: Close (sent 634B received 996B)
2020/11/18 18:56:07 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#1: Close (sent 634B received 353KB)
2020/11/18 18:56:08 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#3: Open
2020/11/18 18:56:10 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#4: Open
2020/11/18 18:56:14 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#4: Close (sent 634B received 996B)
2020/11/18 18:56:38 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#3: Close (sent 902B received 631KB)
...
2020/11/18 19:29:54 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#75: Open
2020/11/18 19:29:54 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#76: Open
2020/11/18 19:30:11 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#76: Close (sent 634B received 996B)
2020/11/18 19:31:03 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#77: Open

-> Crash client

2020/11/18 19:31:18 server: session#7: Handshaking...
2020/11/18 19:31:18 server: session#7: Verifying configuration
2020/11/18 19:31:18 server: session#7: Failed: server: Server cannot listen on R:52081=>192.168.0.78:554

**Comment by jpillora** [comment]
Does "session#6” close eventually?

**Comment by cedricve** [comment]
Yess it just closed.

2020/11/18 19:40:56.947 GET / 200 1s (10.132.0.60)
2020/11/18 19:46:37 server: session#6: tun: SSH disconnected
2020/11/18 19:46:37 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#75: Close (sent 1.44KB received 710KB)
2020/11/18 19:46:37 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#77: Stream error: ssh: unexpected packet in response to channel open: <nil>
2020/11/18 19:46:37 server: session#6: tun: proxy#R:32540=>192.168.0.101:554: conn#78: Stream error: ssh: unexpected packet in response to channel open: <nil>
2020/11/18 19:46:37 server: session#6: tun: Unbound proxies
2020/11/18 19:46:37 server: session#6: Closed connection (read tcp 10.48.2.42:8000->10.132.0.60:53019: read: no route to host)
2020/11/18 18:55:51.584 GET / 200 50m45s (10.132.0.60)

**Comment by cedricve** [comment]
Could I make it close quicker?

**Comment by cedricve** [comment]
Setting the `keepalive` timer is the way to make the connection close.
