### ISSUE TITLE
Chisel Proxy Authentication

### ISSUE THREAD

**Issue by shantanu561993** [jpillora/chisel#219]
Trying to run chisel behind a corporate proxy. Is there a way I can do a proxy authentication ?

**Comment by jacobleonwoffenden** [comment]
Is this what you're after? https://github.com/jpillora/chisel/blame/master/README.md#L273-L277

**Comment by shantanu561993** [comment]
Kind of auto auth in the case there is a proxy. Sometimes it becomes difficult to get proxy details and the auth becomes difficult. Auto proxy detection can be an option

**Comment by ankushgoel27** [comment]
how do i input the proxy url 

i am using http://domain\user:password@proxyurl.com:3128 but its erroring out on the domain part

**Comment by shantanu561993** [comment]
I am temporarily using a custom C# to provide transport channel to Chisel
