### ISSUE TITLE
Client version (1.7.3) differs from server version (v1.7.3)

### ISSUE THREAD

**Issue by matti** [jpillora/chisel#228]
spams the logs like this

**Comment by LeeJiaLe** [comment]
same issue here, I'm using docker image on aws server

**Comment by jpillora** [comment]
The version string is set using the commit tag, so it should be `v1.X.X` - are the client and server using the same binary?

**Comment by matti** [comment]
in my case I'm running jpillora/chisel on server and brew installed client on the mac

**Comment by jpillora** [comment]
Ah I don’t operate the brew installation... someone else compiles that
version - I’d be wary. I’ll look into it

**Comment by jpillora** [comment]
```
brew install chisel
Updating Homebrew...
==> Downloading https://homebrew.bintray.com/bottles/chisel-2.0.1.big_sur.bottle.tar.gz
```

https://formulae.brew.sh/formula/chisel is another app. How did you install with chisel?

**Comment by tralafiti** [comment]
I'm seeing this, too:
```
2022/03/02 18:13:26 server: session#12: Client version (1.7.7) differs from server version (v1.7.7)
```

Server is using the docker image:
```
docker run --rm -it jpillora/chisel --help                

  Usage: chisel [command] [--help]

  Version: v1.7.7 (go1.17.6)
```

Client downloaded the binary directly from Github:
```
./chisel_1.7.7_darwin_arm64 --help

  Usage: chisel [command] [--help]

  Version: 1.7.7 (go1.17.6)
```


I'm not sure, but maybe this is related to [.github/goreleaser.yml#L8](https://github.com/jpillora/chisel/blob/v1.7.7/.github/goreleaser.yml#L8) using `{{.Version}}` which according to [goreleaser](https://goreleaser.com/customization/templates/#fn:1) gets stripped of v prefixes?

**Comment by matti** [comment]
prob related: https://github.com/weaveworks/eksctl/pull/4873

**Comment by Montralis** [comment]
Is this still relevant?

**Comment by tralafiti** [comment]
Yes, issue still persists, but now the docker image is missing all version info:

```shell
% ./chisel_1.10.0_darwin_arm64 -version
1.10.0

% docker run --rm -it jpillora/chisel:1.10.0 -version


% docker run --rm -it jpillora/chisel:1.10.0 -help

  Usage: chisel [command] [--help]

  Version:  (go1.22.5)
...
```

Upon connecting:
```
2024/09/20 10:24:39 server: session#1: Client version (<unknown>) differs from server version (1.10.0)
```

**Comment by jpillora** [comment]
Ahh will fix

**Comment by tralafiti** [comment]
Thank you! 

Docker Images now contain a version string again, but I fear we are back to the start of the ticket: Binary in Docker-Image reports it's version prefixed with a `v` while the normal binaries a build with a version without this prefix, as described in https://github.com/jpillora/chisel/issues/228#issuecomment-1057853872 resulting in version miss-match log entries.
