### ISSUE TITLE
Multi-architecture Docker builds

### ISSUE THREAD

**Issue by pbstriker38** [jpillora/chisel#245]
Use Docker buildx to build multi-architecture images.

https://docs.docker.com/buildx/working-with-buildx/

*edit: No need to modify the Dockerfile

```shell
docker buildx build --push --platform linux/amd64,linux/arm64,linux/ppc64le,linux/386,linux/arm/v7 --tag pbstriker38/chisel:1.7.4 .
```

https://hub.docker.com/r/pbstriker38/chisel/tags?page=1&ordering=last_updated

**Comment by jpillora** [comment]
Awesome, I've been meaning to add multi arch docker builds. Does automated docker hub builds support it? If not, could you send a PR using github actions instead?

**Comment by pbstriker38** [comment]
I have not tried it though automated docker builds. I've been meaning to search if `docker buildx` is supported in github actions. I've only used for my personal projects since we aren't using any ARM nodes in proruction yet.

Did a quick Github actions search and it looks like there a few pre-built actions for using `docker buildx` 👍 

I'll see if I can make some time to open a PR.

**Comment by jpillora** [comment]
Sounds good
