### ISSUE TITLE
Chisel client behind a proxy

### ISSUE THREAD

**Issue by Arno0x** [jpillora/chisel#25]
Hi,

I can't seem to find the option to specify an upstream proxy on the client side. The objective would be to support a chisel client that has to connect through an authenticated (NTLM) proxy in order to connect to the chisel server.

Any options ?
Thanks.
Arno

**Comment by jpillora** [comment]
There's a PR for using an unauthenticated HTTP CONNECT proxy #14 which you could try

**Comment by Arno0x** [comment]
I can't seem to be able to git clone this PR since it's from "unknown repository" ... ?

**Comment by jpillora** [comment]
Looks like its been deleted, though the [file changes](https://github.com/jpillora/chisel/blob/3427c4ae2adae157f99990ca044e1f423ddb50cf/client/client.go) still exist

**Comment by jpillora** [comment]
chisel now has HTTP CONNECT support in `1.2.0`, please update, see `chisel client --help`, test it out and let me know if there are any issues
