### ISSUE TITLE
AArch64 architecture

### ISSUE THREAD

**Issue by ptorrent** [jpillora/chisel#254]
Hello there !

Is there a way to make chisel works on "AArch64" architecture ?

Thanks for your help !

**Comment by jpillora** [comment]
Both `AArch64` and `arm64` mean ARM 64bit architecture. See releases ending in `_arm64`

**Comment by ptorrent** [comment]
that's what I thought but I get this error when I try to execute chisel

**Comment by ptorrent** [comment]
I'm trying on a raspberry and I've exactly the same problem.. any ideas ?

curl https://i.jpillora.com/chisel! | bash
