### ISSUE TITLE
Is it possible to implement sth like ngrok?

### ISSUE THREAD

**Issue by tpoxa** [jpillora/chisel#285]
I wonder if it is possible to put a reverse proxy server on a wildcard domain and make the external hostname a part of a tunnel system.

Thanks.

**Comment by xlmnxp** [comment]
you can do it
you need to enable reverse proxy in server
```
sudo chisel server --reverse
```

and on client you can reverse the port to server 
in this example I will reverse Minecraft port (25565) to port 30 in the server

```
chisel client 193.122.77.49:8080 R:30:25565
```

now you can connect to the server and it will reverse the connect to your local server
`<server_ip>:30` will redirect you to Minecraft Server

same thing can be done to Http server
