### ISSUE TITLE
[Feature request] Reverse tunnel support

### ISSUE THREAD

**Issue by penguinpowernz** [jpillora/chisel#29]
It would be awesome to see this offer reverse port forwards as well as local port forwards.

**Comment by penguinpowernz** [comment]
How to extend the remote spec to signal remote port forward? Prefix with an R? Make the centre colon an equals sign?

**Comment by jpillora** [comment]
So this would make the server listen/accept connections and the client terminate them? I have another plan to allow clients to make connections https://github.com/jpillora/chisel/issues/9 though since it's quite a large change I decided not to include it in the `1.2` release

**Comment by penguinpowernz** [comment]
Oh I'm thinking SSH protocol... perhaps I misunderstood the SSH related lines in your code.

Internally do you use SSH to do the local port forwards?  If so we could simply use that to enact remote port forwards.

**Comment by jpillora** [comment]
No, internally, I use the SSH protocol. The SSH program implements it, so chisel would also need to implement it.

**Comment by abraiante** [comment]
I second this. Initially I thought this was what Chisel did, but when setting it up I noticed it was the other way around.

My use case:

I have a local (like in the client) HTTP service, that I want to expose to the internet. Chisel is running on the server and I would to set-up a reverse tunnel, so issuing for instance, in the server a 

`
wget http://localhost:8080
`

would open a connection to a port in the client where the HTTP service is offered.

The reverse tunnel would be set-up when Chisel clients connects to the server, and as @penguinpowernz mentioned it could be described in the command-line with something like the thing SSH client uses:

```
-L [bind_address:]port:host:hostport
             Specifies that the given port on the local (client) host is to be forwarded to the given host and port on the remote side.  This works by allocating a socket
             to listen to port on the local side, optionally bound to the specified bind_address.  Whenever a connection is made to this port, the connection is forwarded
             over the secure channel, and a connection is made to host port hostport from the remote machine.

 -R [bind_address:]port:host:hostport
             Specifies that the given port on the remote (server) host is to be forwarded to the given host and port on the local side.  This works by allocating a socket
             to listen to port on the remote side, and whenever a connection is made to this port, the connection is forwarded over the secure channel, and a connection is
             made to host port hostport from the local machine.
```

This would make chisel one of the most versatile hole-punching firewall tools I know.

**Comment by vizv** [comment]
> Initially I thought this was what Chisel did, but when setting it up I noticed it was the other way around.

That's exactly what I thought... After I setup the server, I found it's impossible to do the reverse tunneling.

Adding reverse tunnel support will be nice.

**Comment by hanscees** [comment]
Same here. This means the project page could use soms user scenario samples.

**Comment by jpillora** [comment]
I plan on merging this fork https://github.com/mcbernie/chisel at some point (supports using clients as proxy endpoints) and then with the chisel server also acting as a client (server can also provide `remote`s), then it would result in this functionality.

**Comment by smerschjohann** [comment]
How is the status about this plan? Can I help with something?

**Comment by gedw99** [comment]
Me too. Did this get merged ?

**Comment by steom** [comment]
we who love the holes are all eagerly waiting

**Comment by neculaesei** [comment]
hey, is there any update on when/if this will land in chisel?

**Comment by segator** [comment]
very robust and stable, but we need reverse tunneling.

**Comment by gedw99** [comment]
There is one around by the Rightscale / Goa design developer

check It out to see if you like it.

https://github.com/rightscale/wstunnel

**Comment by sunshineco** [comment]
Pull request #72 implements reverse port forwarding.

**Comment by jpillora** [comment]
#72 has been merged. @mcbernie's implementation (https://github.com/mcbernie/chisel) looks good though I haven't tested it. It could still be merged one day still though for now, I chose @sunshineco's implementation for its simplicity. chisel now implements remote forwarding like SSH. Search "reverse" in the README for more info, in short:

```
    When the chisel server has --reverse enabled, remotes can
    be prefixed with R to denote that they are reversed. That
    is, the server will listen and accept connections, and they
    will be proxied through the client which specified the remote.
```
