### ISSUE TITLE
chisel server not using AUTH-envVar

### ISSUE THREAD

**Issue by andrasj** [jpillora/chisel#295]
I was trying to set up a chisel server in a docker container, and wanted to add a single user.
While reading the 'usage' I saw I should be able to just and the envVar 'AUTH'. However tests showed authentication was not working, I only get it to work by using the cmdline arg --auth.

After checking the sources I noticed the AUTH envVar is only implemented for the client.

After all I think it's better to use the --authfile, but it is confusing that the 'usage' is mentioning non-functioning features :-)

PS. chisel is a great little project. Keep up the good work!

**Comment by jpillora** [comment]
interesting, this is very old bug - strange that it was never mentioned. thanks for the report 👍

**Comment by jpillora** [comment]
Fixed in https://github.com/jpillora/chisel/commit/59e5362e6bd6c0ea3e02f99209a1359416a952aa#diff-2873f79a86c0d8b3335cd7731b0ecf7dd4301eb19a82ef7a1cba7589b5252261
