### ISSUE TITLE
Client should exit/fail if it not able to bind to the local port

### ISSUE THREAD

**Issue by gurjeet** [jpillora/chisel#31]
If one tries to run multiple chisel clients, possibly talking to different hosts, but mistakenly uses the same local port, the second invocation should fail and complain loudly.

```
./chisel client -v --keepalive 10s https://first-host 5022::2022 &
./chisel client -v --keepalive 10s https://second-host 5022::2022
```

The second invocation continues to run despite encountering the error (silent error!). This leads to false sense of success, and subsequent attempts to communicate to `second-host` via local port 5022 will actually forward traffic to `first-host`.

Below is slightly modified output from an actual run:
```
$ ./chisel client -v --keepalive 10s https://second-host 5022::2022
2017/04/13 12:38:32 client: Connecting to wss://second-host:443
2017/04/13 12:38:32 client: 0.0.0.0:202#1: listen tcp4 0.0.0.0:5022: bind: address already in use
2017/04/13 12:38:33 client: Fingerprint 6e:37:2b:d4:76:28:35:12:36:a3:ae:b1:59:10:77:3e
2017/04/13 12:38:33 client: Sending configurating
2017/04/13 12:38:33 client: Connected (Latency 30.839892ms)
```

**Comment by jpillora** [comment]
Fixed this [last week](https://github.com/jpillora/chisel/blob/master/client/proxy.go#L31), update to `1.2` and you'll see messages like:

```
2017/04/14 13:12:43 client: tunnel#1 127.0.0.1:1080=>socks: listen tcp4 127.0.0.1:1080: bind: address already in use
```

**Comment by gurjeet** [comment]
Yes, I am aware of that message; it's on line 2 of the output of the snippet I posted. But it's a violation of [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

Can you at least add a new flag, which is off by default to support existing users, that implements this behaviour?

**Comment by jpillora** [comment]
Point being, it's not silent. Though agreed, it should exit. Since it's mostly a CLI app, I'll just change the behavior I think :+1:
