### ISSUE TITLE
Unrecoverable ssl handshake error

### ISSUE THREAD

**Issue by Congelli501** [jpillora/chisel#32]
During chisel's normal operation, I had this error:
```
ssh: handshake failed: websocket: close 1006 (abnormal closure): unexpected EOF
````

The client is on a bad network so that's probably what caused the error. The problem is that the tunnel went down for good and chisel didn't stop ether.

If this kind of fatal error occurs, can you either:
 - try / catch and retry to open the tunnel
 - exit the process with a non-null exit code so that it may be restarted

Can it be related to this code ?
https://github.com/jpillora/chisel/blob/master/client/client.go#L160

**Comment by jpillora** [comment]
Ah that's strange, chisel should break the connection-retry loop on this
line <https://github.com/jpillora/chisel/blob/master/client/client.go#L198> and
then exit. Can you reliably reproduce?

**Comment by Congelli501** [comment]
No, the error is too sparse to reproduce (it happened once on 9 clients during a month).

I create multiple tunnels in a single process. Can other, still running tunnel block the process from exiting (I don't know if the ssl handshake is shared along multiple tunnel of a single process) ?

**Comment by Congelli501** [comment]
I haven't seen this issue for a while.
In the meantime, I updated chisel and my https reverse proxy, so the issue seems to be resolved.
