### ISSUE TITLE
[Feature request] Option to Ignore TLS certificate verification

### ISSUE THREAD

**Issue by kmlxk** [jpillora/chisel#34]
(Sorry for my poor English)
Chisel is an amazing tool! I want to use chisel behind Nginx.
Becasuse the firewall of my company only allow port 443 use HTTP CONNECT  command. 
I want to use port 443 for my home server for HTTPS website, and chisel too. 
So I tried to config Nginx to redirect HTTPS request by different domain.

[Client Command]
chisel_windows_amd64.exe client --proxy http://company-proxy:port https://home-server:443 0.0.0.0:33389:192.168.1.102:3389

2017/05/26 11:34:54 client: Retrying in 100ms...

**Comment by kmlxk** [comment]
Just now I sniffed chisel https request and get this message:
TLSv1.2	61	Alert (Level: Fatal, Description: Bad Certificate)
How to disable SSL certification verify?

**Comment by jpillora** [comment]
Currently you can't, though you can get a real certificate from let's
encrypt. One way is to use caddy instead of nginx (
https://github.com/jpillora/chisel/issues/28#issuecomment-292696574),
they're quite similar though I think caddy is much better - single binary,
auto HTTPS and more

**Comment by kmlxk** [comment]
@jpillora Thank you very much. 
Nginx SSL reverse proxy can redirect by domain correctly.  
So I tried to modified the following file to ignore SSL certification error .
File: chisel-master\src\github.com\jpillora\chisel\vendor\github.com\gorilla\websocket\client.go
Line: 302
Add code: cfg.InsecureSkipVerify = true
It works for me. Hope this would help others.
THANK YOU again for this great tool!

**Comment by jpillora** [comment]
Releasing this in `v1.7.0-rc7`
