### ISSUE TITLE
Add SNI Spoofing support

### ISSUE THREAD

**Issue by ilovefornite797** [jpillora/chisel#352]

**Comment by jpillora** [comment]
Can you test by editing the client tls config:

https://pkg.go.dev/crypto/tls#Config

	// ServerName is used to verify the hostname on the returned	//
certificates unless InsecureSkipVerify is given. It is also included
	// in the client's handshake to support virtual hosting unless it is
	// an IP address.
	ServerName string <https://pkg.go.dev/builtin#string>


If it works, happy to merge a PR
