### ISSUE TITLE
Disconnect without retry

### ISSUE THREAD

**Issue by tramchamploo** [jpillora/chisel#374]
I'm in a bad network condition and sometimes they break your connection directly.
I think Chisel should retry connecting in this senario rather than giving up.
```
2022/08/14 14:51:56 client: tun: proxy#*=>socks: conn#100: Stream error: ssh: unexpected packet in response to channel open: <nil>
2022/08/14 14:51:56 client: Disconnected
2022/08/14 14:51:56 client: Connection error: read tcp *->*: read: connection timed out
2022/08/14 14:51:56 client: Give up
```

**Comment by jpillora** [comment]
Just merged https://github.com/jpillora/chisel/pull/362 just need to release it

You can use it by installing from source

**Comment by tramchamploo** [comment]
Work like a charm, thanks.
