### ISSUE TITLE
default User-Agent

### ISSUE THREAD

**Issue by epsi1on** [jpillora/chisel#387]
First thanks for great application,
I had trouble using chisel as a socks server, so did some tries and debugs. finally turn out my docker hosting banned the default golang user agent, which is `Go-http-client/1.1`.
Any request with this header is dropped automatically before it arrives to the chisel server and a 403 status code is shown. this is an example dumped traffic from chisel client with chisel server 

-------
data from client to chisel server:
```
GET / HTTP/1.1
Host: ***
User-Agent: Go-http-client/1.1
Connection: Upgrade
Sec-WebSocket-Key: ZlZk/GtDUbxolVT482CRiw==
Sec-WebSocket-Protocol: chisel-v3
Sec-WebSocket-Version: 13
Upgrade: websocket
```
Response from server:
```
HTTP/1.1 403 Forbidden
Server: nginx/1.17.8
Date: Sat, 29 Oct 2022 11:58:25 GMT
Content-Type: text/html
Content-Length: 153
Connection: keep-alive

<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.17.8</center>
</body>
</html>
```
chisel error in this case would be something like `Bad handshake` (which is reported several times in the issues)

but if `User-Agent: Go-http-client/1.1` is removed from headers, then the problem will be solved. i did checked it with a custom python script:

---------
data from client to chisel server (without `User-Agent` header)
```
GET / HTTP/1.1
Host: ***
Connection: Upgrade
Sec-WebSocket-Key: ZlZk/GtDUbxolVT482CRiw==
Sec-WebSocket-Protocol: chisel-v3
Sec-WebSocket-Version: 13
Upgrade: websocket
```
Response from server:
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: rQHtRfyV0jl1afCuMBejkWcpOs8=

�SSH-chisel-v3-server
(some binary data removed)
```

Is there any option to change the default `User-Agent` HTTP header or remove it?
Thanks

**Comment by jpillora** [comment]
Can change it with the -header option
