### ISSUE TITLE
can't establish TLS tunnel

### ISSUE THREAD

**Issue by WTFThatPerson** [jpillora/chisel#397]
I try obfuscate Wireguard traffic, so I installed chisel
When I set plain http tunnel
```
server
sudo chisel server --host <WIRE_SERVER> -p 443

client
sudo chisel client <WIRE_SERVER>:443 <WIRE_PORT>/udp
```

I have success with connection, but if I try skip to https
```
server
sudo chisel server --tls-key <SOME_PATH_1>/key.pem --tls-cert <SOME_PATH_2>/cert.pem --host <SERVER> -p 443

client
sudo chisel client --tls-ca <SOME_PATH_3>/CAcert.pem <WIRE_SERVER>:443 <WIRE_PORT>/udp
```
I have
`client: Connection error: websocket: bad handshake`
I believe, certs are OK, because I use them in stunnel config without any problem. 
It seems I misunderstanding something?

**Comment by jpillora** [comment]
Are you testing on localhost?

If not test both client and server on the same machine

If still working, use mkcert to create test certs

**Comment by WTFThatPerson** [comment]
openssl req -new -x509 -sha256 -days 3650 -nodes -subj "/C=US/CN=127.0.0.1" -newkey rsa:2048 -out lhost.pem -keyout key.pem
Then
`chisel server --tls-key /root/key.pem --tls-cert /root/lhost.pem --host 127.0.0.1 -p 443`
Fall back to TCP while testing, so no /udp on client side
`chisel client --tls-skip-verify 127.0.0.1:443 <SOME_TCP_PORT>`
Still no joy; BTW, client logs "connecting to ws://127.0.0.1:443" not wss. Is it expected?

**Comment by jpillora** [comment]
can you add `was://` or `https://` in front?

default is http https://github.com/jpillora/chisel/blob/master/client/client.go#L75-L77

**Comment by WTFThatPerson** [comment]
Yes, You're right, adding "https://" works. Shame on me do not catch it by myself. At another hand, it worth add to help, I think.
