### ISSUE TITLE
[Feature request] Add internal HTTP CONNECT proxy server (similar to SOCKS)

### ISSUE THREAD

**Issue by netroby** [jpillora/chisel#42]
Hello , currently chisel has built in socks server. i guess we can easy add http proxy server inside chisel server.

I am made a very tiny http proxy server

https://github.com/netroby/gohttpproxy

**Comment by jpillora** [comment]
This is a good idea :) I'm thinking in addition to a `socks` remote, we can also add an `http` remote. This package https://github.com/elazarl/goproxy provides a simple API (uses a `http.Handler`). I haven't looked too deeply into https://github.com/google/martian yet.
