### ISSUE TITLE
Inbound IP Whielist/Blacklist

### ISSUE THREAD

**Issue by epsi1on** [jpillora/chisel#422]
Hi,
Is there any capability for making a whitelist or blacklist for client IPs?

Thanks

**Comment by LoSunny** [comment]
Not sure if you still need, but I have implemented a it in my fork https://github.com/LoSunny/chisel, please note that reverse connection for IP whitelist / blacklist is not implemented.
Just add `--whitelist 1.1.1.1/32` or `--blacklist 10.10.0.0/16` to your `chisel client` command

**Comment by epsi1on** [comment]
> Not sure if you still need, but I have implemented a it in my fork https://github.com/LoSunny/chisel, please note that reverse connection for IP whitelist / blacklist is not implemented. Just add `--whitelist 1.1.1.1/32` or `--blacklist 10.10.0.0/16` to your `chisel client` command

Kindly thank you.
