### ISSUE TITLE
[QUESTION] What is the maximum number of clients supported by a server?

### ISSUE THREAD

**Issue by tom342178** [jpillora/chisel#433]
I have a use case which is low volume and latency tolerant. I am looking to connect a large number of tunnels from remote devices to a central hub and chisel looks like it might be able to serve my needs.

Are there known limitations in the number of clients supported by the server?

**Comment by a-urth** [comment]
Considering server implementation my guess would be that only ram and limit for file descriptors (for opened connections) on the machine you running server, would be your limitations.

**Comment by tom342178** [comment]
thx
