### ISSUE TITLE
Dependabot fake pushes

### ISSUE THREAD

**Issue by bru73f0rc3** [jpillora/chisel#452]
FYI: Please be aware of fake Dependabot pushes:

https://www.securityweek.com/stolen-github-credentials-used-to-push-fake-dependabot-commits/

"As part of the observed campaign, the attackers created a commit message “fix” that appeared to be contributed by the ‘dependabot[bot]’ user account, tricking developers into believing the commits came from GitHub’s tool."

**Comment by jpillora** [comment]
Thanks for the heads up, hackers have such good ideas for hacking lol 

Only I can commit to master, and only master is released so all good here 👍

**Comment by jpillora** [comment]
Ahh yea, i configured for monthly https://github.com/jpillora/chisel/blob/master/.github/dependabot.yml
