### ISSUE TITLE
Chisel defaults to creating an IPv6 socket 

### ISSUE THREAD

**Issue by DanielIsaev** [jpillora/chisel#479]
Hey all, 

I'm not sure why this is happening, but whenever I start a server on my machine using `chisel server -p 8001 --reverse` for example,  the server defaults to creating an IPV6 socket. But I explicitly need an IPv4 socket. This happens even if I omit the `-p` and `--reverse` switches. 
 
I tried searching for this phenomena online but I found nothing. I read the help pages several times but I didn't see any mention of selecting an IP version.  Is there something I'm missing? I really need help on this... 

I'm using chisel version 1.9.1 with GO version 1.21.3 on a Kali 6.5.0-kali3-amd64 VM. 

Thanks in advanced, 
Daniel.

**Comment by claytree82** [comment]
Having the same issue currently as well
