### ISSUE TITLE
Allow force reconnect like `autossh` allows

### ISSUE THREAD

**Issue by vjpr** [jpillora/chisel#51]
`autossh` allows using `pkill -HUP autossh` to make autossh attempt to reconnect immediately.

See https://linux.die.net/man/1/autossh "Controlling SSH".

Use case: When you have a 5 min timeout from the backoff, but you want it to connect immediately without having to restart the process.

**Comment by jpillora** [comment]
https://github.com/jpillora/chisel/releases/tag/1.2.3 released 👍
