### ISSUE TITLE
Question about using a fingerprint and hide credential in base64

### ISSUE THREAD

**Issue by gemini2186** [jpillora/chisel#510]
I have couple questions 😏

I run server like this
`chisel server --keyfile '<key file path>' -p 9312 --socks5`
and i connected like this:
`chisel client --fingerprint '<see server output>' <server-address>:9312 socks`
I discovered that if you do not specify the _--fingerprint_ parameter in the client startup line, the connection will still be successful. Is this how it should be?

How can i hide my credential in base64, when i use parameter --auth. Need an example. It will be like this:
`chisel server --auth | <base64_line> --keyfile '<key file path>' -p 9312 --socks5` ?

Thanks for any help!

**Comment by jpillora** [comment]
> Is this how it should be?

Setting fingerprint on client says "only trust servers with fingerprint", so if you don't set it, you're trusting all servers

> How can i hide my credential in base64

base64 wouldn't hide your credentials, use the `AUTH` env variable instead
