### ISSUE TITLE
Transferring files

### ISSUE THREAD

**Issue by circuitry2** [jpillora/chisel#53]
I have chisel set up successfully and I've established an SSH tunnel between a remote host and my developer machine. I'm connected to the host using a webterm (https://github.com/chjj/tty.js).

I'm wondering if it's possible to use chisel to transfer files to and from my dev machine to the remote host?

Is it possible to set my machine up so that I can scp files to and from these machines, transferring the files using the tunnel that gets set up?

**Comment by jpillora** [comment]
Instead of SSHing over webterm, use chisel to tunnel port 22, and then use normal SSH. Then you can use SCP as normal since it runs over SSH.
