### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by circuitry2** [jpillora/chisel#54]
Hello, I am having a difficult time understanding how to use chisel for my use case.

I have a sever, running "chisel server --port 8080".

I have a client (client A) that is running a webserver on port 80.
I have another client behind a firewall (client B).
I would like client B to be able to view the website hosted on client A's machine.

What types of settings would I use in "chisel client" for each client to allow this to work?

Thank you!!

**Comment by circuitry2** [comment]
Do I need to set chisel up as a reverse proxy?

**Comment by saswatp** [comment]
Let's assume
-  IP address of box A is 20.20.20.20.  You can replace this with your IP address. 
- Web service running on box A runs on port 80
- The example below assumes your web server binds to all hosts including localhost.

1. On machine A,  host chisel server with the following command "sudo chisel server -v --port 8080 &"
2. On machine B (behind firewall) , run chisel client "chisel client -v 20.20.20.20:8080 localhost:80"
3. Run a curl command from your client curl http://localhost/<your webservice endpoint> . You should see content from the webserver you're hosting in box A

**Comment by jpillora** [comment]
Thanks @saswatp

**Comment by DanielDominguezBender** [comment]
Hello,

I'm trying to make something similar to work but on a machine that has no WGET or CURL (pivoting machine).
So I do not know now hot to upload a file and make chisel work.
Any suggestions?

Thx !!
Dan
