### ISSUE TITLE
vpn over chisel

### ISSUE THREAD

**Issue by shashankmjain** [jpillora/chisel#58]
Is there an option to use the tun/tap devices with ssh to have a vpn implemented over chisel instead of doing port forwarding?

**Comment by jpillora** [comment]
Possible though outside of the scope of this project, would be a new
project with deeper hooks into the OS with much more OS specific code

**Comment by shashankmjain** [comment]
Ok. Thanks. Would be good to have anyways

**Comment by jainsm** [comment]
Let us know if you need any contribution?

**Comment by jpillora** [comment]
Will close as dupe of #3

**Comment by jpillora** [comment]
Thanks @jainsm though I think this is out of scope, as it would result in too big of a change. Pulls in requirements around routing and ip address management
