### ISSUE TITLE
Option to stop retries after hard timeout limit

### ISSUE THREAD

**Issue by schulzh** [jpillora/chisel#62]
It would be nice to have a client option to limit the retries to a specified amount of time, so it does not retry indefinitely.
This is useful to monitor the connection of "daemonized" tunnels; one can set-up a bash script which opens the tunnel, and if chisel exists (because it fails to re-establish the connection in x amount of time) e.g. an alert email could be sent.
Currently chisel does not exit and tries to reconnect forever, which is hard to monitor from bash scripts.

**Comment by jpillora** [comment]
There's a PR for this https://github.com/jpillora/chisel/pull/47. I just need to merge it.

**Comment by schulzh** [comment]
@jpillora As far as I can see, this is not the same feature request. The #47 is providing a way to customize the maximum retry *interval* from the currently hardcoded 5 minutes. I am asking for a timeout *limit*, after which chisel should give up and exit with an error.
