### ISSUE TITLE
[Feature request] Any interest in server supporting many-to-many connections for remote mgt of IOT devices or other use cases?

### ISSUE THREAD

**Issue by armor99** [jpillora/chisel#63]
My use case is being able to SSH into 1000's of embedded devices that are behind a firewall. I've been looking at creating a supervisor app for your server that would listen on a std port for connection requests from devices, and then create new instances respectively. The supervisor app would also need to provide some sort of directory service to clients wishing to connect to devices.

**Comment by jpillora** [comment]
This would be nice to have, but probably out of scope for this project. I'm working on a closed source VPN which could do this, though unfortunately it's not ready yet.
