### ISSUE TITLE
Why chisel reconnect heroku server  every 30 minutes?

### ISSUE THREAD

**Issue by wangyi2005** [jpillora/chisel#66]
2018/07/24 20:00:32 client: Connecting to wss://#########.herokuapp.com:443
2018/07/24 20:00:32 client: tunnel#1 127.0.0.1:1080=>socks: Listening
2018/07/24 20:00:51 client: Fingerprint 25:00:8b:b5:0f:fa:55:e6:c2:d2:ce:55:87:d9:e1:da
2018/07/24 20:00:52 client: Connected (Latency 321.5073ms)
2018/07/24 20:36:14 client: Retrying in 100ms...
2018/07/24 20:36:29 client: Fingerprint c8:57:de:07:33:ce:2d:6a:50:63:50:86:eb:ab:6c:a1
2018/07/24 20:36:30 client: Connected (Latency 310.4464ms)
2018/07/24 21:11:59 client: Retrying in 100ms...
2018/07/24 21:12:08 client: Retrying in 200ms...
2018/07/24 21:12:27 client: Fingerprint ca:6e:9f:be:c5:ce:12:31:01:d6:3f:65:17:ad:0f:77
2018/07/24 21:12:29 client: Connected (Latency 320.8896ms)
2018/07/24 21:46:07 client: Retrying in 100ms...
2018/07/24 21:46:28 client: Fingerprint 50:a7:05:e8:bb:2d:a4:f8:d7:ad:42:89:1a:ea:c5:f8
2018/07/24 21:46:29 client: Connected (Latency 322.6522ms)

**Comment by jpillora** [comment]
Use the keep alive option

**Comment by wangyi2005** [comment]
chisel.exe client  --keepalive 60s --auth user:pass  https://######.herokuapp.com:443 socks

2018/07/25 13:20:50 client: Connecting to wss://######.herokuapp.com:443
2018/07/25 13:20:50 client: tunnel#1 127.0.0.1:1080=>socks: Listening
2018/07/25 13:20:52 client: Fingerprint db:3d:78:e8:5b:27:b5:9f:ab:06:6f:f7:0c:6c:7f:2e
2018/07/25 13:20:53 client: Connected (Latency 228.4157ms)
2018/07/25 13:38:01 client: Retrying in 100ms...
2018/07/25 13:38:03 client: Fingerprint db:3d:78:e8:5b:27:b5:9f:ab:06:6f:f7:0c:6c:7f:2e
2018/07/25 13:38:04 client: Connected (Latency 258.4338ms)
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#25: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: Retrying in 100ms...
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#27: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#28: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#29: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#30: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#31: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#32: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#33: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:20:33 client: tunnel#1 127.0.0.1:1080=>socks: conn#26: Stream error: ssh: unexpected packet in response to channel open: <nil>
2018/07/25 14:21:13 client: Fingerprint bd:e0:b7:10:1f:63:9a:43:5d:dc:50:cb:40:70:ee:0e
2018/07/25 14:21:14 client: Connected (Latency 253.8532ms)

**Comment by jpillora** [comment]
Try using a keep alive of 25s
