### ISSUE TITLE
New docker image is missing ca-certificates

### ISSUE THREAD

**Issue by Congelli501** [jpillora/chisel#69]
I switched to the latest chisel version & docker image, and I can't establish connections toward https enabled server anymore (Let's encrypt certificate).

Running `apk add ca-certificates` within the new docker image before running chisel client solves the problem.
Could you add `ca-certificates` in the published docker image ?
BTW, it would be nice to tag the docker image by version, to allow quick rollbacks ;).

Thanks for your great work !

**Comment by jpillora** [comment]
Ah yes! Will republish. Will look into template tagging now hub supports it

**Comment by jpillora** [comment]
Republished as `latest`, I think future releases should also get tagged `release-<version>`
