### ISSUE TITLE
Help required to install chisel in MacBook Pro Mojave

### ISSUE THREAD

**Issue by subbu-calgary** [jpillora/chisel#70]
I need help to install chisel in MacbookPro Mojave.  Any help will be much appreciated.

**Comment by jpillora** [comment]
Do you want to use it in the terminal? Download the binary and `./chisel --help`

Do you want to run it as a service? Download the binary and follow https://medium.com/@chetcorcos/a-simple-launchd-tutorial-9fecfcf2dbb3
