### ISSUE TITLE
Client/server version incompatibility

### ISSUE THREAD

**Issue by dsmid** [jpillora/chisel#71]
When the newest client 1.2.4 tries to connect server 1.2.2 it gets this error:
`2018/11/15 09:31:07 client: ssh: handshake failed: ssh: overflow reading version string`

On the other hand, when an older client (version < 1.2.4) tries to connect server 1.2.4 it gets this error instead:
`2018/11/15 09:57:33 client: ssh: handshake failed: websocket: close 1006 (abnormal closure): unexpected EOF`

Client < 1.2.4 vs Server < 1.2.4 and Client 1.2.4 vs Server 1.2.4 works fine.

**Comment by jpillora** [comment]
Yeah there were ssh protocol updates, I could release 1.2.4 again with a
proper error message though I couldn't make it work unfortunately

**Comment by dsmid** [comment]
Descriptive and helpful error messages would be nice.
There's no problem in upgrading both sides of the tunnel, the problem was I hadn't got the slightest idea what was going on and what went wrong.

**Comment by jpillora** [comment]
This is fixed in 1.2.5 and 1.3.0 (auto-release in progress), didn't want to re-release 1.2.4 since its been out for a while
