### ISSUE TITLE
authfile not working

### ISSUE THREAD

**Issue by enzokwai** [jpillora/chisel#74]
Issue
I am not able to start chisel server when using authfile option, it output fatial error and exit.

Everything is normal when not using authfile

I am try to use sample authfile in github still no luck

Context
λ chisel server --port 8020 --authfile users.json
2019/01/04 18:35:28 server: users: Loading the configuraion from: users.json
fatal error: sync: Unlock of unlocked RWMutex

goroutine 1 [running]:
runtime.throw(0x845eb3, 0x20)
/app/.heroku/go/src/runtime/panic.go:608 +0x79 fp=0xc00007fb08 sp=0xc00007fad8 pc=0x42d4b9
sync.throw(0x845eb3, 0x20)
/app/.heroku/go/src/runtime/panic.go:594 +0x3c fp=0xc00007fb28 sp=0xc00007fb08 pc=0x42d42c
sync.(*RWMutex).Unlock(0xc000005500)
/app/.heroku/go/src/sync/rwmutex.go:124 +0xa8 fp=0xc00007fb58 sp=0xc00007fb28 pc=0x46e1c8
github.com/jpillora/chisel/share.(*UserIndex).loadUserIndex(0xc0000051a0, 0x846157, 0x21)
/tmp/cloudgox/080f9a4f2cc2/gopath/src/github.com/jpillora/chisel/share/users.go:151 +0x702 fp=0xc00007fcb0 sp=0xc00007fb58 pc=0x72a262
github.com/jpillora/chisel/share.(*UserIndex).LoadUsers(0xc0000051a0, 0xc000018180, 0xa, 0x0, 0xcb)
/tmp/cloudgox/080f9a4f2cc2/gopath/src/github.com/jpillora/chisel/share/users.go:78 +0xdc fp=0xc00007fd10 sp=0xc00007fcb0 pc=0x7299bc
github.com/jpillora/chisel/server.NewServer(0xc00007fec0, 0xa, 0x0, 0x0)
/tmp/cloudgox/080f9a4f2cc2/gopath/src/github.com/jpillora/chisel/server/server.go:63 +0xa9a fp=0xc00007fdf8 sp=0xc00007fd10 pc=0x76468a
main.server(0xc000084020, 0x4, 0x6)
/tmp/cloudgox/080f9a4f2cc2/gopath/src/github.com/jpillora/chisel/main.go:174 +0x4d4 fp=0xc00007ff18 sp=0xc00007fdf8 pc=0x766544
main.main()
/tmp/cloudgox/080f9a4f2cc2/gopath/src/github.com/jpillora/chisel/main.go:54 +0x245 fp=0xc00007ff98 sp=0xc00007ff18 pc=0x765f25
runtime.main()
/app/.heroku/go/src/runtime/proc.go:201 +0x207 fp=0xc00007ffe0 sp=0xc00007ff98 pc=0x42ee57
runtime.goexit()
/app/.heroku/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00007ffe8 sp=0xc00007ffe0 pc=0x457711

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
/app/.heroku/go/src/runtime/sigqueue.go:139 +0xa3
os/signal.loop()
/app/.heroku/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
/app/.heroku/go/src/os/signal/signal_unix.go:29 +0x48

**Comment by patrick-othmer** [comment]
Fix: https://github.com/jpillora/chisel/pull/77
