### ISSUE TITLE
Disable Encryption

### ISSUE THREAD

**Issue by 0xjohn** [jpillora/chisel#75]
I want to disable encryption and accept connection without ssh handshake, is it possible to disable chisel encryption?

**Comment by matti** [comment]
Isn't chisel connection secure when the server runs behind https (or wss) - disabling encryption would make sense in that situation.

**Comment by jpillora** [comment]
Yep, it would make sense to disable encryption if you're already running over HTTPS. Unfortunately, SSH [appears not to support a NULL cipher](https://github.com/golang/crypto/blob/4def268fd1a49955bfb3dda92fe3db4f924f2285/ssh/common.go#L28-L42) so it would be a very large change to use an alternate multiplex/control protocol, most likely a rewrite.
