### ISSUE TITLE
remote server is behind NAT

### ISSUE THREAD

**Issue by joeblew99** [jpillora/chisel#8]
i have a situation where i have some embedded devices out in the field and they are all in NAT environment. They can only call upstream on 80 and 443.

So i am hoping i could use this to connect to them via a public static in between server, using Chisel.

But i am not sure.. Can you let me know what you think..

**Comment by jpillora** [comment]
Chisel isn't suited for server to client connections yet. I would recommend
tinc. I've got tinc on my raspberry pi and wherever it is, it'll join my
private tinc network and I can reach it.

**Comment by joeblew99** [comment]
Ok just had a quick read on tinc.
It does mesh networking.

It sounds very much like weave, a golang project. You know it ?

**Comment by joeblew99** [comment]
Starting point :)https://groups.google.com/a/weave.works/forum/m/#!msg/weave-users/VPdMCcVWVjc/n9PovgNmCAAJ

**Comment by joeblew99** [comment]
Solvedhttps://github.com/weaveworks/weave/issues/1566

**Comment by jpillora** [comment]
interesting, a pure go solution would be nice. looks like there's still a some work to do though to get it working dockerless though
