### ISSUE TITLE
High RAM usage on ARM

### ISSUE THREAD

**Issue by ChaturGopalkrishna** [jpillora/chisel#88]
Hi,

I needed to use Chisel on ARM. I cross compiled it and reduced the binary size using the following two commands:
_env GOOS=linux GOARCH=arm go build -ldflags "-w -s"
~/go/src/github.com/pwaller/goupx/goupx --brute chisel_

However, when I run the chisel binary on the ARM board (512MB RAM), I find that it is taking a huge amount of RAM.
The "top" yeilds an output of usage of 161% and 775m! However, the difference of output of "free" command taken before and after the execution of chisel client is ~6MB.
I ran strace too, and the sum of all mmap2 memory allocated is 700MB+. 
The command I executed to connect to the server:

_./chisel client --fingerprint <> 10.137.12.88:2002 127.0.0.1:9191:10.137.12.88:9191_

Is there some way to optimize / reduce the RAM usage? 
Any pointers would be helpful!

Thanks,
Chatur G

**Comment by ChaturGopalkrishna** [comment]
@jpillora Request your help on this!

**Comment by patrick-othmer** [comment]
What happend when you not using goupx? UPX is not recommend with go binaries.

**Comment by jpillora** [comment]
Yep agreed with @patrick-othmer, upx is your issue

**Comment by giacomovalenti** [comment]
Hi, I can I have a look on the copiled chisel for arm? giacomovalenti@protonmail.com

**Comment by jpillora** [comment]
Just released https://github.com/jpillora/chisel/releases/tag/v1.4.0 see
downloads
