### ISSUE TITLE
every minute: client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by daald** [jpillora/chisel#94]
First of all, thanks for this nice, compact, fast, stable and easy-to-use tool.

However, there's a little issue: I use the client on a workstation which I hibernate overnight. The next day, new connections work as expected. But there seems to be a problem that the interrupted connection doesn't completely terminate:

> 2019/05/28 15:49:11 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/05/28 15:49:11 client: Retrying in 100ms...
2019/05/28 15:49:11 client: Handshaking...
2019/05/28 15:49:11 client: Fingerprint aa:bb:cc:dd:7d:44:5e:36:82:0e:9e:66:f4:f5:62:1b
2019/05/28 15:49:11 client: Sending config
2019/05/28 15:49:11 client: Connected (Latency 34.1538ms)

The above block of messages repeats every minute

Client: 1.3.1 chisel_windows_amd64.exe
Server: have to look at home but is self-built from sources on Linux ~ same version

**Comment by jpillora** [comment]
Looks like there's a some device in the middle timing out your connections. Try the keep alive setting:

```
$ chisel client --help
...
    --keepalive, An optional keepalive interval. Since the underlying
    transport is HTTP, in many instances we'll be traversing through
    proxies, often these proxies will close idle connections. You must
    specify a time with a unit, for example '30s' or '2m'. Defaults
    to '0s' (disabled).
...
```

**Comment by daald** [comment]
What I want to say: there's no reason to close the same connection every minute again. Chisel should forget about this connection and just make a new one

```
2019/07/23 09:54:45 client: Handshaking...
2019/07/23 09:54:45 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 09:54:45 client: Sending config
2019/07/23 09:54:45 client: Connected (Latency 34.8518ms)
2019/07/23 09:55:45 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 09:55:45 client: Retrying in 100ms...
2019/07/23 09:55:45 client: Handshaking...
2019/07/23 09:55:45 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 09:55:45 client: Sending config
2019/07/23 09:55:45 client: Connected (Latency 34.1504ms)
2019/07/23 09:56:45 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 09:56:45 client: Retrying in 100ms...
2019/07/23 09:56:45 client: Handshaking...
2019/07/23 09:56:45 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 09:56:45 client: Sending config
2019/07/23 09:56:45 client: Connected (Latency 35.9034ms)
2019/07/23 09:57:45 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 09:57:45 client: Retrying in 100ms...
2019/07/23 09:57:45 client: Handshaking...
2019/07/23 09:57:46 client: Fingerprint e3:xx:xx:xx:e5
```

And again: These messages don't appear in a 8h session after starting up, but the day after (after standby [which is in fact some kind of "device in the middle which timed out"]) every minute.

I assume that the client still thinks that the connection is intact (and is unable to change that state), while the server had time overnight to forget about it.

**Comment by daald** [comment]
I see now, it was a client (VLC) which kept the connection open for some time (35 minutes!). After this, the messages were gone. Maybe chisel client has the option to close the connection on that side?

**Comment by jpillora** [comment]
Oh okay, does adding the keepalive option fix it?

**Comment by daald** [comment]
no, didn't change anything.

```
2019/07/23 16:26:23 client: Sending config
2019/07/23 16:26:23 client: Connected (Latency 35.958544ms)
2019/07/23 16:27:23 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 16:27:23 client: Retrying in 100ms...
2019/07/23 16:27:24 client: Handshaking...
2019/07/23 16:27:24 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 16:27:24 client: Sending config
2019/07/23 16:27:24 client: Connected (Latency 37.71718ms)
2019/07/23 16:28:24 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 16:28:24 client: Retrying in 100ms...
2019/07/23 16:28:25 client: Handshaking...
2019/07/23 16:28:25 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 16:28:25 client: Sending config
2019/07/23 16:28:25 client: Connected (Latency 37.023542ms)
2019/07/23 16:30:22 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 16:30:22 client: Retrying in 100ms...
2019/07/23 16:30:22 client: Handshaking...
2019/07/23 16:30:23 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 16:30:23 client: Sending config
2019/07/23 16:30:23 client: Connected (Latency 43.194477ms)
2019/07/23 16:31:23 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 16:31:23 client: Retrying in 100ms...
2019/07/23 16:31:23 client: Handshaking...
2019/07/23 16:31:23 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 16:31:23 client: Sending config
2019/07/23 16:31:23 client: Connected (Latency 36.961136ms)
2019/07/23 16:32:23 client: Connection error: websocket: close 1006 (abnormal closure): unexpected EOF
2019/07/23 16:32:23 client: Retrying in 100ms...
2019/07/23 16:32:24 client: Handshaking...
2019/07/23 16:32:24 client: Fingerprint e3:xx:xx:xx:e5
2019/07/23 16:32:24 client: Sending config
2019/07/23 16:32:24 client: Connected (Latency 54.603149ms)
```
(here it is a ssh session)

**Comment by jpillora** [comment]
Try with keepalive and see if it helps

**Comment by daald** [comment]
that was with keepalive

**Comment by jpillora** [comment]
What did you set it to? `30s`? Either way, looks like a host somewhere along your route is closing your connection. If keepalive doesn't help, not sure if chisel can do anything to fix this

**Comment by daald** [comment]
with keepalive 20s, I didn't see this message anymore.

**Comment by jpillora** [comment]
:+1:
